### ISSUE TITLE
Documents : augmenter la limite de poids

### ISSUE THREAD

**Issue by Spone** [telabotanica/naturadapt#104]
Il faudrait pouvoir ajouter des fichiers jusqu'à 5 Mo dans les groupes

**Comment by zemax** [comment]
Tu vois où ça se règle chez CleverCloud ? Normalement c'est le `upload_max_filesize` et `post_max_size` de Apache/PHP ?

**Comment by Spone** [comment]
Je pense qu'il faut utiliser le procédé décrit ici : https://www.clever-cloud.com/doc/php/php-apps/#configure-your-php-applications

**Comment by zemax** [comment]
La limite était déjà de 32M normalement.
C'est la limite affichée dont tu parles ?

**Comment by Spone** [comment]
Ah oui en effet, y a-t-il moyen de rendre cette limite affichée dynamique ?

**Comment by Spone** [comment]
32 Mo pour les documents
5 Mo pour les images

**Comment by zemax** [comment]
Résolu sur 0fce6ef2b536f6f4c38eb0b7ae6d624e1c011868
Une limite de 32M est définie pour les documents, 5M pour les autres fichiers.
La taille est affichée dynamiquement comme le minimum entre la taille définie et la limite du serveur.
