### ISSUE TITLE
Menu déroulant du profil non accessible sur mobile

### ISSUE THREAD

**Issue by Spone** [telabotanica/naturadapt#105]
Le menu déroulant ne fonctionne pas sur mobile. Il s'affiche mais l'image de profil prend le clic et la page est rechargée avant qu'on ait eu le temps de cliquer sur un élément du sous-menu

**Comment by zemax** [comment]
Du coup je retire le lien pour le transformer en bouton de toggle ?

**Comment by Spone** [comment]
Oui je pense qu'il vaut mieux faire ça, et donc mettre le lien plutôt dans le menu déroulant.

**Comment by Spone** [comment]
Pour préciser, on aurait donc :

- sur écrans tactiles, un menu qui s'ouvre au touch sur l'avatar
- sur les autres devices, le menu s'ouvre au hover

Les items du menu déroulant :

- Tableau de bord
- Mon profil (lien vers le profil affiché, et non l'édition du profil)
- Déconnexion

**Comment by zemax** [comment]
Corrigé en preview sur 4178e438bbf31547961fbb393b01fde9d8dbbc2c

**Comment by Spone** [comment]
Super, merci pour ta réactivité !
