### ISSUE TITLE
Champ non limité à 32 caractères

### ISSUE THREAD

**Issue by Spone** [telabotanica/naturadapt#106]
![image](https://user-images.githubusercontent.com/38524/60092997-9d0fab00-9748-11e9-842c-4e609c41edd1.png)

Ce champ devrait être limité à 32 caractères mais certaines personnes ont pu mettre des textes plus longs.

Il faudrait ajouter une validation côté client et côté serveur

**Comment by zemax** [comment]
Fixé sur 4a902cb3aeb5ab6fa1b104d9da1cf5cb4b8d7b86

**Comment by Spone** [comment]
Comment ça se passe pour les champs déjà complétés ?

**Comment by zemax** [comment]
Ils seront coupés à 32 caractères à l'affichage et à l'enregistrement

**Comment by Spone** [comment]
OK, on va peut-être perdre des données du coup. Je me dis qu'il faudrait peut-être manuellement retoucher les enregistrements qui posent problème pour déplacer le contenu "en trop" dans le champ "Bio". Je le fais en base dans phpMyAdmin ?

**Comment by zemax** [comment]
Quand on voit https://naturadapt.com/groups/communaute/members , est-ce que 32 c'est suffisant ?

**Comment by verovs** [comment]
les users se sont adaptés et ils ont du renommer leur présentation depuis si besoin, je clos
