### ISSUE TITLE
Image de profil cassée

### ISSUE THREAD

**Issue by Spone** [telabotanica/naturadapt#108]
https://naturadapt.com/members/26

https://naturadapt.com/media/cache/resolve/avatar/user-26/IMG_6781_Hugo_Lecomte.jpeg

**Comment by zemax** [comment]
Pb de limite mémoire sur le redimensionnement de l'image
```
PHP message: PHP Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 24576 bytes)
```

**Comment by Spone** [comment]
Comment gérer ce cas du coup ?

**Comment by zemax** [comment]
Sur le commit 478a7780f37380e63550f89cde445d514b354494, j'ai rajouté un `.user.ini` dans `public/` pour passer :
- le `memory_size` à 256M
- l'upload à 5M (il était à 32M par défaut)

**Comment by zemax** [comment]
Du coup ça passe.
