### ISSUE TITLE
Ajouter les partenaires

### ISSUE THREAD

**Issue by Spone** [telabotanica/naturadapt#109]
> Faire apparaître le bandeau des partenaires sur la page d'accueil (ou un "lien utile" : "Les partenaires du projet NaturAdapt")

Voir sous quelle forme

Il y a par exemple cela à la fin des newsletters actuelles :

![image](https://user-images.githubusercontent.com/38524/60104108-15826600-9761-11e9-8e4c-2df9d7f926db.png)

**Comment by verovs** [comment]
c'est fait ça !
