### ISSUE TITLE
Liste de membres cliquable

### ISSUE THREAD

**Issue by Spone** [telabotanica/naturadapt#112]
Il faudrait que l'ensemble de ce bloc soit cliquable (un seul lien) pour accéder à l'annuaire du groupe en question :

![image](https://user-images.githubusercontent.com/38524/60105701-1ec10200-9764-11e9-9554-93eb531f3d57.png)

Endroits concernés :

![image](https://user-images.githubusercontent.com/38524/60105732-2aacc400-9764-11e9-90c0-fb927a2730be.png)

![image](https://user-images.githubusercontent.com/38524/60105751-37311c80-9764-11e9-8875-09503d43d37a.png)

**Comment by zemax** [comment]
résolu sur b98990daecbe2f62cf900ae8ede8aaa175166735
