### ISSUE TITLE
Amélioration responsive

### ISSUE THREAD

**Issue by Spone** [telabotanica/naturadapt#114]
Avec du vrai contenu, on a du scroll latéral sur les petits écrans :

![Screen Shot 2019-06-25 at 16 22 42](https://user-images.githubusercontent.com/38524/60106457-8a579f00-9765-11e9-94fa-759123e6fe9a.png)

**Comment by zemax** [comment]
Corrigé sur 43cba46c53755d4723076669590e6348322730b1 et suivants
A recetter voir s'il reste des bugs
