### ISSUE TITLE
Améliorer la preview des icônes

### ISSUE THREAD

**Issue by Spone** [telabotanica/naturadapt#116]
Étant donné que les icônes sont affichées sous forme de ronds dans l'interface, ce serait bien que la preview (lors de la sélection d'un fichier local) soit ronde également.

![image](https://user-images.githubusercontent.com/38524/60112629-749ba700-9770-11e9-9f9c-62133be3d38e.png)

(idem dans l'édition du profil)

**Comment by zemax** [comment]
Corrigé sur c90a47263865a61ef339754acdf2554e622d7f0b
