### ISSUE TITLE
Aide "pourquoi créer un groupe ?"

### ISSUE THREAD

**Issue by Spone** [telabotanica/naturadapt#117]
Il serait pertinent d'avoir un peu de contenu, accessible en haut du formulaire de création de groupe, qui explique un peu quels sont les cas d'usages pour des groupes.

En fait cela correspondrait à cette page sur le site de Tela Botanica https://www.tela-botanica.org/projets/creer-un-projet/

**Comment by verovs** [comment]
ouep  bien vu ! note à moi même avoir une charte de défini

**Comment by verovs** [comment]
On a cette page désormais : https://naturadapt.com/groups/plateforme-web/pages/qui-peut-creer-des-groupes
on pourrait y mettre un lien sur le form

**Comment by verovs** [comment]
pt être profiter de la mise en place modération (si elle nécessite de modif le "template créer groupe")  #196 
Pour ajouter une ligne au form là dessus ?

**Comment by Spone** [comment]
@verovs la modération se fait sur des écrans séparés donc on devrait pas avoir à modifier la page de création de groupe. A moins que tu veuilles y ajouter une mention du fait que le groupe va être modéré avant d'apparaître sur le site ?

**Comment by verovs** [comment]
@Spone ok ! par contre  je pensais (mais sans l'avoir formulé) que lorsqu'on cliquait sur "créer le groupe" au lieu d'avoir une notif "groupe créé", on aurait "votre groupe est en cours de validation" (un truc comme ça)

C'est vrai que ajouter une mention sur le form serait certainement bien... mais en fait on a plus que 5 jours donc... on va faire au mini et un jour j’essaierai d'ajouter le texte par moi même , comme une grande : )

**Comment by Spone** [comment]
Je verrais bien ça comme mentions en haut du form :

![image](https://user-images.githubusercontent.com/38524/96242380-b4108700-0fa3-11eb-91b5-5b1dc75ea91b.png)

Voilà le HTML correspondant si tu veux le modifier @verovs 

```html
<p>Vous pouvez demander la création d'un nouveau groupe. Avant de commencer, jetez un oeil à la page <a href="#TODO">Pourquoi créer un groupe ?</a></p>
<p>Votre groupe devra être validé par un administrateur de la communauté avant d'apparaître sur le site.</p>
```

**Comment by ya-web** [comment]
vous êtes sûrs que pour ça la meilleure option c'est de mettre le texte sur un groupe de discussion sur les évolutions de la plateforme ? Je vais être obligé de mettre en dur `{{ path('group_page_index', { 'groupSlug': 'plateforme-web', 'pageSlug': 'qui-peut-creer-des-groupes' }) }}` dans le code c'est pas génial, ça pourrait pas aller dans une page de `communauté ` le groupe par défaut qui a sa variable en conf et qu'on peut changer, et je mettrai aussi le slug de la page d'aide en conf ce serait mieux non?

**Comment by verovs** [comment]
Au niveau code c'est peut-être pas bien ça je sais pas mais au niveau éditorial tout ce qui a trait à l'utilisation plateforme va dans le groupe plateforme. :)

**Comment by Spone** [comment]
Je suis plutôt d'accord avec @ya-web 

Sinon peut-être qu'on peut laisser dans le groupe Plateforme et mettre en config :
- le slug du groupe Plateforme
- le slug de la page

Qu'en pensez-vous ?

**Comment by verovs** [comment]
si ça permet de laisser ça là ou c'est ok !

**Comment by verovs** [comment]
mais du coup mon comit il va pas et je peux pas le faire moi même :(

**Comment by ya-web** [comment]
@verov c'est prêt t'inquièt' et ton commit allait pas très bien il yavait 2-3 petites choses à changer j'ai juste à mettre la conf en place et ça va tourner

**Comment by verovs** [comment]
d'acc cool :) je veux bien que tu me dises ce qui allait pas dans le commit par contre pour apprendre ;)

**Comment by ya-web** [comment]
#210

**Comment by verovs** [comment]
![Capture d’écran de 2020-10-26 11-48-04](https://user-images.githubusercontent.com/22638189/97163583-28f07780-1781-11eb-9d32-0fac2d8a5849.png)
La première phrase n'apparait pas, pourtant c'est bien mergé et il me semble déployé aussi

**Comment by verovs** [comment]
ok c'est bon

**Comment by ya-web** [comment]
> ![Capture d’écran de 2020-10-26 11-48-04](https://user-images.githubusercontent.com/22638189/97163583-28f07780-1781-11eb-9d32-0fac2d8a5849.png)
> La première phrase n'apparait pas, pourtant c'est bien mergé et il me semble déployé aussi

Juste pour répondre à ça si le lien n'est pas fonctionnel la première phrase n'apparait pas, c'est voulu. Sinon il me faut une phrase alternative sans lien.
