### ISSUE TITLE
Ajouter une carte "Discussions : bientôt disponible" sur les projets

### ISSUE THREAD

**Issue by Spone** [telabotanica/naturadapt#121]
Histoire que les utilisateurs puissent déjà se projeter dans les futures fonctions de la plateforme, on pourra ajouter dès maintenant une carte "Discussions" :

![image](https://user-images.githubusercontent.com/38524/60117785-1a541380-977b-11e9-8cad-f8921c2a307c.png)

Texte à copier-coller :

> Cette fonction est en cours de développement, vous pourrez bientôt discuter à l'intérieur de ce groupe au sein de la plateforme et par e-mail.

**Comment by zemax** [comment]
en 2nd position comme sur la maquette ?

**Comment by Spone** [comment]
Oui. J'ai vu que tu l'as fait comme ça :+1:
