### ISSUE TITLE
Toujours trier les membres dans le même ordre

### ISSUE THREAD

**Issue by Spone** [telabotanica/naturadapt#122]
Il faudrait que l'ordre des membres dans la carte :

![image](https://user-images.githubusercontent.com/38524/60159752-30ea8100-97f4-11e9-985b-6051c92b9272.png)

et ici :

![image](https://user-images.githubusercontent.com/38524/60162174-46ae7500-97f9-11e9-8f2e-22d33a3852b7.png)

reprenne celui de l'annuaire :

![image](https://user-images.githubusercontent.com/38524/60159882-698a5a80-97f4-11e9-9247-8193677ccb50.png)

**Comment by zemax** [comment]
fixé sur 3c676bee1138136792204f9fdb307bf3932ac289 : les membres sont triés par date décroissante d'adhésion au groupe
