### ISSUE TITLE
Cartes groupes et images de profil : enlever les couleurs fluo

### ISSUE THREAD

**Issue by Spone** [telabotanica/naturadapt#124]
Quand une image a été définie, enlever la couleur de `background` pour éviter d'avoir un flash coloré avant que l'image charge :

![image](https://user-images.githubusercontent.com/38524/60162312-92611e80-97f9-11e9-9a88-18c936cd7658.png)
![image](https://user-images.githubusercontent.com/38524/60162348-a147d100-97f9-11e9-9bc8-0400c78af69c.png)

**Comment by zemax** [comment]
Couleur supprimée sur 5f15dd36b9ea185da32ccb6aa9d8f7228b516cdf
