### ISSUE TITLE
Différencier les title selon les pages

### ISSUE THREAD

**Issue by Spone** [telabotanica/naturadapt#125]
Actuellement c'est quasiment toujours "Communauté", il faudrait différencier le contenu de la balise `<title>` selon les pages.

**Comment by zemax** [comment]
C'est assez simple à régler via le template, soit selon un pattern (cf https://github.com/telabotanica/naturadapt/blob/develop/templates/pages/page/page-index.html.twig) soit pour une page spécifique comme la liste des groupes
Des règles particulières à appliquer ?

**Comment by Spone** [comment]
Je pense qu'on peut à chaque fois avoir le titre du contenu affiché (nom du groupe, titre de la page, titre de l'actu, nom de l'utilisateur etc.) et avoir "NaturAdapt" pour la page d'accueil.

**Comment by zemax** [comment]
Défini sur le commit f4004eeeb10b8bc6069e7bf09211ca5ad09cf0c1
