### ISSUE TITLE
Icône de groupe non-carrée

### ISSUE THREAD

**Issue by Spone** [telabotanica/naturadapt#126]
Quand on ajoute une image rectangulaire, l'icône s'affiche comme ça :

![image](https://user-images.githubusercontent.com/38524/60169298-ba0ab380-9806-11e9-932e-775f8cbd1a90.png)

**Comment by zemax** [comment]
Ok... Je vais le forcer avec du CSS (cdbba748e325f8538b25e84785fe0a18e835b6c1)
Je ne comprend pas pourquoi le filtre de resize n'est pas correctement appliqué.
