### ISSUE TITLE
Si le nom du groupe est trop long (et qu'on y est inscrit) alors le logo du groupe devient ovale

### ISSUE THREAD

**Issue by verovs** [telabotanica/naturadapt#129]
screen de la prod
![Capture d’écran de 2019-06-26 15-24-58](https://user-images.githubusercontent.com/22638189/60193813-96606100-9838-11e9-95b5-46e7e3985969.png)

reproduction et testable sur staging ici : https://naturadapt.etamin.studio/groups/un-nom-tres-long-pour-reproduire-le-comportement-logo-ovaleuuuuh

**Comment by verovs** [comment]
bon en fait sur mon exemple le nom est tellement long qu'il n'y a pas besoin d'etre inscrit au groupe pour que le logo se déforme ^^ https://naturadapt.etamin.studio/groups/un-nom-tres-long-pour-reproduire-le-comportement-logo-ovaleuuuuh

**Comment by zemax** [comment]
C'est corrigé
