### ISSUE TITLE
Etre ajoutée / m'ajouter /  en admin des groupes créés

### ISSUE THREAD

**Issue by verovs** [telabotanica/naturadapt#130]
On a créé quelques groupes ( : fait créer par autrui). Les admins m'ont tjs pas acceptés. Les groupes sont pas 'remplis' (y'a pas de photos, ça fait pas 'propre').
J'aimerai pouvoir ajouter au moins les photos, car c'est pas sur qu'ils pensent/aient le temps de m'accepter / de revenir sur leur groupe pour le compléter, pendant le séminaire et même lundi et en début de semaine.

Idéalement il faudrait que je sois admin de tous les premiers groupes créés, pour pouvoir agir indépendamment si besoin. Le but n'est pas que je le reste advitam eternam.
est-ce qu'il existe une manip simple, (une ligne de code à modifier en m'expliquant comment remplir ? ou autre, aucune idée), pour que je puisse m'add admin si besoin (idéalement il faut pas que ce soit automatique,si le groupe se remplit, j'ai rien à y faire) ?
Si vous avez des idées / suggestions / conseils / avis :)

**Comment by zemax** [comment]
En me logguant sur le server je t'ai donné les droits Admin sur la plateforme : tu as accès à toutes les opérations (approbation de membres, modifications de groupe, etc...)

**Comment by verovs** [comment]
Merci beaucoup, c'est parfait :)
