### ISSUE TITLE
Corriger les blocs d'adhésion des groupes 

### ISSUE THREAD

**Issue by chikencheesenaan** [telabotanica/naturadapt#132]
Corriger les blocs adhésion au groupes qui s'agrandissent en même temps que le contenu texte lorsque l'on clique sur "en savoir plus" 

<img width="1137" alt="Capture d’écran 2019-06-27 à 16 38 33" src="https://user-images.githubusercontent.com/45854391/60276430-e3593b80-98fb-11e9-8053-20ee6b01037a.png">

**Comment by zemax** [comment]
corrigé sur 08074fdd331c80271215e9953ad8e2585e51fac7
