### ISSUE TITLE
plateforme down (IMPORTANT)

### ISSUE THREAD

**Issue by verovs** [telabotanica/naturadapt#133]
https://naturadapt.com  8h49 AM vendredi

**Comment by Spone** [comment]
Je suis en train de regarder. Tout à l'air normal côté Clever Cloud, j'ai contacté leur support.

**Comment by verovs** [comment]
merci !

(et bonjour ^^ )

**Comment by Spone** [comment]
C'est un problème au niveau de la validation du propriétaire du domaine, @verovs s'occupe de relancer RNF à ce sujet.
