### ISSUE TITLE
Modifier son mail

### ISSUE THREAD

**Issue by verovs** [telabotanica/naturadapt#134]
Pour l'instant il n'est pas possible de modifier l'email avec lequel on s'est inscrit⋅e sur la plateforme. Ce champ n'est pas dispo sur l'edit du profil 
![Capture d’écran de 2019-07-02 11-00-16](https://user-images.githubusercontent.com/22638189/60499461-c97f7600-9cb8-11e9-9322-1c1ce684f135.png)

**Comment by Spone** [comment]
@zemax si besoin, est-ce que je peux modifier le mail d'un utilisateur en base ou est-ce que ça risque de poser des problèmes ?

**Comment by zemax** [comment]
Ajouté sur e14c201614940e8968e42a925d5f2c2224dac2d4
