### ISSUE TITLE
Document : organiser dans des dossiers

### ISSUE THREAD

**Issue by Spone** [telabotanica/naturadapt#135]
Essayer d'estimer le temps de dév pour cette fonction

- Possibilité de créer / supprimer des dossiers (les documents alors contenus dans le dossier se retrouvent dans ce cas "sans dossier")
- Possibilité de placer un document dans un seul dossier (ou dans aucun)
- Un seul niveau de profondeur
- Ajouter un filtre permettant d'afficher seulement les documents d'un dossier donné
- Dans la liste de tous les documents, grouper par dossier avec des "intertitres" (nom du dossier)

**Comment by zemax** [comment]
J'ai poussé sur develop (2c37d23e2a42c593990ee0b15588c54e9aa5f4a3)
- Possibilité de spécifier un Dossier quand on crée un Document
- Possibilité de modifier un Document (pour le moment son titre et son dossier) et de le supprimer

![image](https://user-images.githubusercontent.com/286485/67404480-c1bf4680-f5b3-11e9-9314-05a51c1e5f4b.png)

Des remarques sur la meilleure façon de présenter les dossiers ?

**Comment by verovs** [comment]
ça marche bien ! (et aussi la suppression de doc :)  )
https://naturadapt.etamin.studio/groups/vive-le-nord/documents
Il faut aussi penser à une différence pour les fichiers hors dossiers.
par exemple ici les deux derniers fichiers ne sont dans aucun dossiers mais apparaissent comme faisant partie de "dossier & apoströphê"

![Capture d’écran de 2019-10-25 15-51-50](https://user-images.githubusercontent.com/22638189/67576831-9f5a3400-f73f-11e9-80da-57007d481f54.png)

Comme les gens adorent les dossiers, je me dis qu'on pourrait prévoir pt-être un système d'accordéon pour cacher l’intérieur/déplier ? Pt-être pour le futur ?

sinon @chikencheesenaan et @Spone  pour les suggestions d'affichage des dossiers 
parce que moi si tu mets simplement une icone style "file" en face du titre, ça me va ^^

**Comment by Spone** [comment]
Je pense qu'on peut simplement augmenter la taille du nom des dossiers à `1.3rem` et leur ajouter de la marge au-dessus (`padding: 3rem 1.25rem 1.25rem;`).

Ça donne ça :

![image](https://user-images.githubusercontent.com/38524/67621958-1f9e9900-f815-11e9-805d-3bf2354d3677.png)

**Comment by zemax** [comment]
La modification de la font ainsi qu'un bouton de folding sont intégrés sur 94d2e8eb2d6e174adc8187ce060865c42f5022db

**Comment by Spone** [comment]
C'est trop collé en haut Maxime tu peux ajouter de la marge entre le champ de recherche et le nom du premier dossier ?
![image](https://user-images.githubusercontent.com/38524/68870374-1493a600-06fb-11ea-9378-919f2bd9add2.png)

Sinon tu as une solution pour l'affichage des fichiers hors-dossier, comme l'évoquait @verovs ?

**Comment by Spone** [comment]
C'est trop collé en haut Maxime tu peux ajouter de la marge entre le champ de recherche et le nom du premier dossier ?
![image](https://user-images.githubusercontent.com/38524/68870374-1493a600-06fb-11ea-9378-919f2bd9add2.png)

Sinon tu as une solution pour l'affichage des fichiers hors-dossier, comme l'évoquait @verovs ?

**Comment by zemax** [comment]
J'ai rajouté un margin-top sur 2472bc863e1400443b882ba81de031a41b776686

**Comment by zemax** [comment]
Pour les documents à la racine, ils sont affichés légèrement séparés des autres, mais ce n'est pas très visible

**Comment by Spone** [comment]
On peut peut-être les mettre tout en haut du coup (ce qui ne sont pas dans un dossier) ?

**Comment by zemax** [comment]
Ok, c'est fait sur 6ff1fb54f20d38edfb8783c1e10bc629c1457182

**Comment by verovs** [comment]
trop chouette  les documents !
