### ISSUE TITLE
Articles & pages : Class image-style-side ne fonctionne pas

### ISSUE THREAD

**Issue by verovs** [telabotanica/naturadapt#140]
Sur les actus & pages, on peut choisir via l'éditeur de texte si l'on souhaite uploader une photo en 'pleine page' ou 'sur la droite'

mais en fait ça marche pas :)
ça fonctionne quand on est dans l'éditeur mais dés que l'article/page est postée alors la classe n'a pas d'effet 
exemple : https://naturadapt.etamin.studio/groups/plateforme-web/articles/t-ezr

On choisit ça dans l'éditeur : figure class="image ck-widget image-style-side ck-widget_selected"
![Capture d’écran de 2019-07-11 19-00-40](https://user-images.githubusercontent.com/22638189/61070453-0eb94b80-a40f-11e9-904b-504ddda74b24.png)

et ça devient ça qd c'est publié figure class="image image-style-side"
![Capture d’écran de 2019-07-11 19-05-25](https://user-images.githubusercontent.com/22638189/61070403-e9c4d880-a40e-11e9-99ff-efdbc7808bf8.png)

**Comment by zemax** [comment]
Corrigé sur 96aa6dc4f310e1efb14a250453c868ca5dcdac5b
