### ISSUE TITLE
impossible d'upload une img ds un article (403 forbiden)

### ISSUE THREAD

**Issue by verovs** [telabotanica/naturadapt#148]
Sur le staging : 
je peux pas uploader d'img à l'intérieur de mon article(quand je le créé et/ou que je l'édite).
j'ai essayé avec des petits format (30ko) et des .png et .jpg
Quand j'utilise le wysiwyg: 
je clique sur picto img > ça ouvre mon explorateur fichier là > je choisis mon img > je l'aperçois une fraction de seconde puis j'ai un pop up "couldn't upload " (screen)
![Capture d’écran de 2019-10-21 16-21-38](https://user-images.githubusercontent.com/22638189/67215563-f602fd80-f421-11e9-9671-df4fbe31b72a.png)

La console dit 403 (screen)
![Capture d’écran de 2019-10-21 16-40-13](https://user-images.githubusercontent.com/22638189/67215374-9f95bf00-f421-11e9-8870-f854837d193f.png)

Lien pour tester direct : https://naturadapt.etamin.studio/groups/un-nom-tres-long-pour-reproduire-le-comportement-logo-ovaleuuuuh/articles/bloup-bloup/edit

**Comment by verovs** [comment]
est-ce que c'est "normal" genre c'est un réglage spécial du staging pour pas consommer trop d'espace disque ? C'est chelou qd même

**Comment by zemax** [comment]
Je pense que c'est plutôt une histoire de droits qui ne seraient pas cohérents entre "droit d'écrire un article" et "droit d'uploader un fichier lié au groupe"
Je vais regarder plus en détails, et peut-être être plus permissif sur le droit d'uploader un fichier

**Comment by zemax** [comment]
J'ai poussé une modification, peux-tu me dire si ça te fait toujours l'erreur ?

**Comment by verovs** [comment]
ça marche !
https://naturadapt.etamin.studio/groups/un-nom-tres-long-pour-reproduire-le-comportement-logo-ovaleuuuuh/articles/bloup-bloup
