### ISSUE TITLE
Documents : nombreuses extensions non autorisées

### ISSUE THREAD

**Issue by verovs** [telabotanica/naturadapt#149]
J'ai testé aujourd'hui l'upload de pleins de types de fichiers différents  sur le staging : 
 jpg, jpeg, png : ok
gif : ok
svg : ko
zip : ko
tar.gz : ko
pdf : ok
ppt : ko
doc : ok
xls : ok
odt: ok
odp: ko
ods: ok
txt: ko
csv: ko
mp4: ko
mp3: ko
mm: ko
sla: ko

Est-ce qu'on pourrait en autoriser un peu plus ? (autant effectivement le .sla je pense que ça sera pas vraiment utilisé, autant le ppt & zip surement)

**Comment by Spone** [comment]
A mon avis on peut ajouter :
- svg
- zip
- tar.gz
- ppt
- xlsx
- odp
- txt
- csv

**Comment by zemax** [comment]
J'ai rajouté les mime types manquants sur e15e1e97cea932aaf82fae312d1ade09b3ce77ea
Il faudrait par contre rajouter les icones correspondants ? (ca se fait en CSS via le mime type)

**Comment by Spone** [comment]
Tu peux utiliser https://github.com/telabotanica/naturadapt/blob/develop/public/media/layout/icons/other.png par défaut pour tous ceux qui n'ont pas d'icône spécifique ? On va regarder quelles icônes il faut rajouter.

**Comment by zemax** [comment]
Oui c'est déjà le fallback pour les fichiers
