### ISSUE TITLE
Page de contenu

### ISSUE THREAD

**Issue by Spone** [telabotanica/naturadapt#15]
Page contenu, admin : https://xd.adobe.com/view/fadc33db-9c84-4133-6ae0-c1bd5539049f-8ced/screen/f31e90d7-b0c5-4442-989c-c988888ea290/A-propos-de-la-plateforme-Administrateur?hints=off

Page contenu, non-admin : https://xd.adobe.com/view/fadc33db-9c84-4133-6ae0-c1bd5539049f-8ced/screen/e2c2d325-b5ad-43b5-b8b0-2436a6b6f76f/A-propos-de-la-plateforme-?hints=off

- Titre
- Date de dernière modification
- Contenu rich text
- Sommaire (liste des intertitres de la page ?)
- Table des matières (liste des pages existantes dans le groupe ?) cf. #18 
- Auteur(s) sous forme de carte membre #20

- [x] Faire une version avec un fil d'Ariane (page d'un groupe)

**Comment by valentindb** [comment]
https://xd.adobe.com/view/da3ca5d6-7cd5-4769-586b-d484673d1fe3-ac0d/screen/adb5045e-06f0-4238-88c0-39ea4f715c00/About

**Comment by Spone** [comment]
@valentindb Est-ce que l'idée est d'avoir une image de fond derrière la zone de titre ? ou un aplat de couleur ?
