### ISSUE TITLE
Spécifications liste de discussion / forum

### ISSUE THREAD

**Issue by Spone** [telabotanica/naturadapt#153]
## Principe de base

- Pour chaque groupe, il y a une liste de discussion associée.
- Chaque liste de discussion a un mail dédié (par exemple `communaute@lists.naturadapt.com` pour le groupe "Communauté"), auquel on peut écrire pour lancer une discussion.
- Chaque membre du groupe est automatiquement abonné à la liste, lorsqu'il rejoint le groupe.
- Chaque membre a la possibilité de se désabonner de la liste sans pour autant quitter le groupe.
- Les membres du groupe doivent pouvoir échanger sur cette liste de discussion, uniquement par e-mail (sans jamais visiter la plateforme, à part pour s'inscrire).

## Interface "forum"

- L'historique des messages envoyés sur la liste de discussion est consultable via une interface web accessible aux membres du groupe.
- Les messages sont organisés en "sujets"
- Il est possible de lancer un nouveau sujet à travers un formulaire web.
- Il est possible de répondre à un sujet à travers un formulaire web, présent sur la page de consultation du sujet.

### Lancer une discussion

- Soit l'utilisateur envoie un mail sur l'adresse e-mail dédiée à ce groupe (`slug-du-groupe@lists.naturadapt.com`)
  - Le mail est reçu par Postmark, qui le transmet à la plateforme via un [inbound webhook](https://postmarkapp.com/developer/webhooks/inbound-webhook)
  - La plateforme retrouve le groupe correspondant à l'aide du slug présent dans l'adresse e-mail de destinataire et vérifie que l'adresse e-mail de l'expéditeur correspond à celle d'un membre du groupe
    - Si oui, un sujet est créé dans le groupe, avec comme titre le sujet du mail et comme message le contenu du mail. Ce sujet est associé à l'utilisateur correspondant.
    - Si non, un mail est envoyé à l'expéditeur pour lui indiquer qu'il n'est pas autorisé à poster dans ce groupe
- Soit l'utilisateur crée un nouveau sujet depuis l'interface web
  - Le sujet est alors créé en base et associé à cet utilisateur
- Dans les deux cas, le message est ensuite envoyé par mail à tous les membres du groupe, avec comme adresse d'expéditeur (ou de `Reply-To`, à préciser) une adresse contenant l'identifiant de la discussion (par exemple `communaute+e6dcac49-4bee-41d2-bad5-03e9618da5a6@lists.naturadapt.com`). Cet identifiant est fourni par Postmark dans le champ `MailboxHash`.
  - Pour cet envoi de mails multiples, on utilise l'option "[batch](https://postmarkapp.com/developer/api/email-api#send-batch-emails)" de l'API Postmark

### Répondre à une discussion

- Soit l'utilisateur répond directement à un mail reçu
  - Dans ce cas le mail et reçu par Postmark, qui déclenche un inbound webhook
  - La plateforme retrouve la discussion correspondante à l'aide de l'ID présent dans l'adresse e-mail de destinataire, vérifie l'adresse de l'expéditeur etc. (cf. ci-dessus)
- Soit l'utilisateur poste un message depuis l'interface web
  - Le message est alors créé en base et associé à l'utilisateur
- Le message est ensuite envoyé aux membres du groupe.

## Évolutions possibles (par ordre de priorité)

- support des pièces-jointes
- support des réponses à un message spécifique (à voir si c'est vraiment utile)

## Références et documentation

- Aperçu de la fonction Webhook de Postmark
  https://postmarkapp.com/developer/webhooks/webhooks-overview
- Inbound Webhook (envoyé quand un mail est reçu par Postmark)
  https://postmarkapp.com/developer/webhooks/inbound-webhook
- Explication d'un workflow type d'une fonction "répondre par e-mail"
  https://postmarkapp.com/developer/user-guide/inbound/sample-inbound-workflow
- Envoi d'e-mails multiples avec l'API de Postmark
  https://postmarkapp.com/developer/api/email-api#send-batch-emails

**Comment by verovs** [comment]
un bonus pour l'interface forum : 
 - Il est possible (pour l'admin) de supprimer un message (ou le masquer) de l'interface.  Cela permet de supprimer les spams

**Comment by Spone** [comment]
> Il est possible (pour l'admin) de supprimer un message (ou le masquer) de l'interface.  Cela permet de supprimer les spams

Étant donné que seuls les membres du groupe peuvent poster, on devrait pas mal limiter le spam, mais en effet c'est à prévoir par la suite.

**Comment by zemax** [comment]
(Je reprends ici les commentaires qui ont pu être fait sur le XD et par mail)

- Les administrateurs peuvent masquer un message
- On se posait la question de la nécessité du WYSIWYG en effet. Si on le garde, on laisse que gras, italique, liste et peut-être lien ?
- Ça serait bien d'avoir la possibilité de mettre des fichiers, type "PJ".

**Comment by zemax** [comment]
J'en profite pour noter mes réflexions un peu en vrac :
 - J'ai démarré le développement cette semaine par l'interface Web, qui est bien sûr plus simple à tester. En effet pour les mails et le webhook, il faudra nécessairement le tester sur une interface accessible de l'extérieur, c'est à dire sur le serveur de recette ?
- Les pièces jointes ne me semblent pas problématiques lors de la création d'un message (via le web ou via email) . Il y a cependant un risque d'y intégrer toutes les pièces jointes "fantomes" (images de signatures, etc...) ? Et dans le mail envoyé aux autres membres, il vaut pieux que ces pièces jointes soient intégrées comme liens ?
- Concernant le formattage des messages : vu les contraintes des emails HTML, la mise en page web > email risque d'être très limitée aux balises "simples" :  gras, italique, lien...
- Les éléments à prendre en compte lors du parsing email > web :
  - supprimer les signatures  (sur quels critères ? ce qui est après un -- ?)
  - nettoyer le code HTML ?

**Comment by verovs** [comment]
J'ajoute à : Les éléments à prendre en compte lors du parsing email > web :
 - supprimer (si possible) les mails "quotés" : quand on répond à un mail, la majorité du temps on laisse les mails précédents en dessous.
- supprimer les" headers" des mails 
- supprimer les mails en clair ? Je veux bien des avis là dessus.

Pour :  Et dans le mail envoyé aux autres membres, il vaut pieux que ces pièces jointes soient intégrées comme liens ?  J'ai pas vraiment d'avis.
Pour  : On se posait la question de la nécessité du WYSIWYG en effet. Si on le garde, on laisse que gras, italique, liste et peut-être lien ?  oui pas vraiment besoin de plus je trouve ?

**Comment by Spone** [comment]
Pour la problématique des citations et signatures : @zemax jette un oeil à `StrippedTextReply` dans la [documentation Postmark](https://postmarkapp.com/developer/user-guide/inbound/parse-an-email), ça peut peut-être nous simplifier la tâche.

**Comment by Spone** [comment]
C'est tout bon pour attaquer le dév @zemax ? Si tu veux qu'on se cale un coup de fil dans la semaine tu me dis ?

**Comment by zemax** [comment]
Salut Hans,

J'espère que tu vas bien?

Je voudrais tester le Inbound de Postmark, est-ce que tu peux le brancher
sur
https://naturadapt.etamin.studio/ws/list/inbound/d604c886-bd00-440f-9bd7-684672f2df5e
?
On peut s'appeler pour en parler quand tu veux.

A ta dispo,

Maxime

Le lun. 3 févr. 2020 à 11:19, Hans Lemuet <notifications@github.com> a
écrit :

**Comment by Spone** [comment]
Salut @zemax 

C'est fait : 

![image](https://user-images.githubusercontent.com/38524/75140430-308de700-56ef-11ea-9dc2-4e6b62c8df22.png)

Attention l'adresse e-mail à utiliser pour les tests est `nom-du-groupe@lists.naturadapt.etamin.studio`
