### ISSUE TITLE
User sans username 

### ISSUE THREAD

**Issue by verovs** [telabotanica/naturadapt#159]
je sais pas trop comment ils ont réussi à faire ça mais y'a un user "vide"  en prod
Il y a bien son mail sous le lien "contact"
https://naturadapt.com/members/51

![Capture d’écran de 2019-12-13 16-53-55](https://user-images.githubusercontent.com/22638189/70813888-921a0700-1dca-11ea-923c-ab7429c942e9.png)

ça signifierait qu'ils ont bien cliqué sur le lien mail "activer mon compte" mais ce sont arrêté là, sans sauvegarder les modifs ?
![Capture d’écran de 2019-12-13 17-04-33](https://user-images.githubusercontent.com/22638189/70813939-afe76c00-1dca-11ea-9ce7-3c16815e8cdc.png)

En même temps, logiquement à leur prochaine connexion ils devront remplir leur profil avant d'accéder à quoi que ce soit si c'est ça ?

**Comment by Spone** [comment]
C'est normal je pense, c'est que l'utilisateur a créé son compte mais n'a pas encore confirmé son mail et créé son profil. @zemax tu confirmes ?

Il faudrait peut-être le masquer de la liste des membres du coup ?

**Comment by zemax** [comment]
J'ai implémenté ça pour les non-admin sur da0f5656185fcf6a2acff0e2d846c9d77ffd03ce

**Comment by verovs** [comment]
j'ai créé un compte avec pouletroti  yopmail.com


![Capture d’écran de 2020-04-01 11-37-06](https://user-images.githubusercontent.com/22638189/78122774-80a64a80-740d-11ea-82c4-2c46f2383b1f.png)
j'ai cliqué sur "activer le compte" mais j'ai pas rempli mon compte
![Capture d’écran de 2020-04-01 11-37-22](https://user-images.githubusercontent.com/22638189/78122897-aa5f7180-740d-11ea-98a4-55f7e7bb9efd.png)

je vois pas poulet roti dans https://naturadapt.etamin.studio/members \o/
Je vois pas quoi tester de plus ? Je clos
