### ISSUE TITLE
notif "vous êtes déjà connectée" qd je clique sur créer 1 sujet

### ISSUE THREAD

**Issue by verovs** [telabotanica/naturadapt#172]
Si :
-  sur un groupe public, 
- dont je ne suis pas membre
- et qui n'a pas encore de discussion

je clique sur Créer votre première discussion > Créer un sujet
Alors je suis renvoyée en page d'accueil avec une notif " vous êtes déjà connectée "
![Capture d’écran de 2020-03-09 17-02-03](https://user-images.githubusercontent.com/22638189/76233638-c6b22900-6228-11ea-9a2e-84e98fa183e5.png)

> je devrai plutôt déclencher une notif "vous devez rejoindre le groupe pour créer un sujet"

**Comment by zemax** [comment]
Corrigé sur 41811ec01062ca7aa562d621f7c5eee9e0183d9a

**Comment by verovs** [comment]
![Capture d’écran de 2020-03-24 16-42-36](https://user-images.githubusercontent.com/22638189/77446282-80df8e00-6dee-11ea-9500-709d7fa2cfff.png)
nickel !
