### ISSUE TITLE
discussion via reply mail essayer d'enlever le [date] Bot etamin a écrit

### ISSUE THREAD

**Issue by verovs** [telabotanica/naturadapt#173]
je ne sais pas trop comment formuler ceci : 
Si je réponds à une discussion via email alors le contenu de la notif n’apparaît pas dans l'interface plateforme mais il reste la ligne "le 10/03/2012 Bot Etamin a écrit"

![Capture d’écran de 2020-03-09 17-17-02](https://user-images.githubusercontent.com/22638189/76234625-4260a580-622a-11ea-9f34-6232ff12ead0.png)

![Capture d’écran de 2020-03-09 17-19-07](https://user-images.githubusercontent.com/22638189/76234645-47bdf000-622a-11ea-89fa-6c7c6110f4b1.png)

**Comment by zemax** [comment]
Ça devrait être fixé (en recette) avec 17b35a92fb8debaf6f63389cc464b413e2a69d6b

**Comment by verovs** [comment]
![Capture d’écran de 2020-03-24 16-34-57](https://user-images.githubusercontent.com/22638189/77445624-97d1b080-6ded-11ea-9085-f9816dceb13a.png)
ça marche :)

**Comment by Spone** [comment]
Au top !

Ma PR a été mergée https://github.com/willdurand/EmailReplyParser/pull/73 dès qu'il y a une nouvelle version on pourra upgrader @zemax

**Comment by Spone** [comment]
@zemax tu peux passer à la v2.9.0 : https://github.com/willdurand/EmailReplyParser/releases/tag/2.9.0

**Comment by zemax** [comment]
C'est fait.
Mais comme il y a d'autres espace-insécables dans le mail de test (en début de ligne), j'ai laissé le remplacement manuel. A la limite on pourrait juste les supprimer en début et fin de ligne.
