### ISSUE TITLE
discussion : afficher les PJ

### ISSUE THREAD

**Issue by verovs** [telabotanica/naturadapt#175]
Rendre les pièces jointes visibles sur l'interface / par mail

(on avait eu une discussion là dessus sur le XD et/ou par mail mais je n'y ai plus accès)

**Comment by verovs** [comment]
en fait on en a parlé ici sûrement : https://github.com/telabotanica/naturadapt/issues/153

**Comment by Spone** [comment]
@chikencheesenaan voilà à quoi ça ressemble dans les mails reçus :

![image](https://user-images.githubusercontent.com/38524/77894864-32127800-7276-11ea-9967-c107e369d9dc.png)

Dans l'historique de discussion :

![image](https://user-images.githubusercontent.com/38524/77894504-a993d780-7275-11ea-836a-a2f7ccbc068a.png)

https://naturadapt.etamin.studio/groups/plateforme-web/discussions/b0f9161b-94c2-498b-be03-7a910c430802

Dans le formulaire de réponse :

![image](https://user-images.githubusercontent.com/38524/77894573-c203f200-7275-11ea-99fe-3f64d286e451.png)

**Comment by chikencheesenaan** [comment]
c'est top ! 

Juste pour la réponse mail, j'aurais remonté la section des pièces jointe dans le bloc de réponse pour qu'on comprenne mieux que les deux sont lié et pas passé à coter 
![Capture d’écran 2020-03-30 à 11 40 39](https://user-images.githubusercontent.com/45854391/77898871-22962d80-727c-11ea-8a11-b19464a2422c.png)

**Comment by verovs** [comment]
ça marche bien !
https://naturadapt.etamin.studio/groups/un-nom-tres-long-pour-reproduire-le-comportement-logo-ovaleuuuuh/discussions/a08de3d3-8fc5-4dbc-a368-87e114a16b40

![Capture d’écran de 2020-04-01 11-27-24](https://user-images.githubusercontent.com/22638189/78121610-e1348800-740b-11ea-8340-a64f4e390b96.png)
