### ISSUE TITLE
Désabonnement discussions

### ISSUE THREAD

**Issue by verovs** [telabotanica/naturadapt#176]
2 choses :
 - en fin de mail
 - sur l'interface

(je créé juste le ticket pour qu'on puisse échanger dessus)

**Comment by Spone** [comment]
@chikencheesenaan il faudrait faire deux écrans supplémentaires pour Naturadapt :

## Gestion de l'inscription à un groupe

Ce premier écran correspond à un menu de gestion de son abonnement quand on est membre d'un groupe.

Actuellement on a :

![image](https://user-images.githubusercontent.com/38524/77337334-0a2c8d00-6d29-11ea-9b85-8d8a092b6bd5.png)

Sur les wireframes on avait un menu déroulant :

![image](https://user-images.githubusercontent.com/38524/77337112-bf127a00-6d28-11ea-8ce9-5c4d2bf5292e.png)

(le menu déroulant à droite)

L'idée serait d'avoir 3 options dans ce menu déroulant, avec une petite explication en-dessous :
- **Abonné(e)** Vous recevez toutes les discussions de ce groupe par e-mail.
- **Membre** Vous pouvez accéder au groupe mais vous ne recevez pas d'e-mail.
- **Quitter le groupe** Vous n'aurez plus accès au groupe.

On pourra éventuellement, à l'avenir, ajouter un niveau supplémentaire pour recevoir seulement un récap hebdomadaire des mails.

L'inspiration est le menu de Github :

![image](https://user-images.githubusercontent.com/38524/77337471-38aa6800-6d29-11ea-8702-9a68d3ed80a2.png)

## Vue d'ensemble des groupes

Ensuite, on aimerait ajouter une rubrique (ou un page à part entière) dans "Mes paramètres". Ce serait une liste de tous les groupes auxquels l'utilisateur est inscrit, avec en face de chacun, le même menu déroulant qui est décrit au-dessus. Cette page permettrait à l'utilisateur d'avoir une vue d'ensemble des groupes dont il fait partie et de gérer son niveau d'abonnement.

**Comment by chikencheesenaan** [comment]
Voici le lien xd avec les écrans demandés : 
https://xd.adobe.com/view/5d0dcbd7-6c40-40b5-5550-8db382ea73e0-2b3c/

Je pense que c'est mieux d'avoir les groupes sur une page à part comme proposé :)

**Comment by zemax** [comment]
Merci.
Par contre pour les utilisateurs qui ont le droit de modifier les infos du groupe, on n'a pas ce bouton 'Inscrit" ; à cet endroit il y a le bouton "Modifier"
Il me semble qu'on avait déjà noté que c'était problématique.
Est-ce que je déplace le bouton "Modifier" sous les infos du groupe, et je met le "Inscrit" pour tout le monde ?

**Comment by zemax** [comment]
J'ai intégré le désabonnement sur la page "Groupe" en recette.
Je vais m'occuper de la page récapitulative "Mes groupes"

**Comment by Spone** [comment]
> Est-ce que je déplace le bouton "Modifier" sous les infos du groupe, et je met le "Inscrit" pour tout le monde ?

Je trouve ça bien comme tu as fait :

![image](https://user-images.githubusercontent.com/38524/77741458-35f38f80-7015-11ea-9a81-42ea4dfc1bcd.png)

**Comment by verovs** [comment]
trop bien, merci bcp, je teste tout ça en début de semaine :)

**Comment by verovs** [comment]
tout marche parfaitement ! abonnement/désabonnement via lien / via page parametres-groupes, via groupe. Top :)
