### ISSUE TITLE
notif "user profil create" en haut de la fenetre

### ISSUE THREAD

**Issue by verovs** [telabotanica/naturadapt#179]
Aucune idée  de comment ça s'appelle
si je ne remplis pas mon profil, et que je clique quand même sur des liens pour me balader sur le site, je suis redirigée à chaque fois sur "complete ton profil" (bien) mais il apparaît, en haut de l'écran, une petite ligne noire avec "user_profile_create"  en vert 

![Capture d’écran de 2020-04-01 11-48-08](https://user-images.githubusercontent.com/22638189/78123912-31f9b000-740f-11ea-9ede-493095271b0e.png)

C'est vraiment un petit détail, sachant qu'on ne veut pas que les gens restent  sans créer leur compte. Je le note quand même parce que je l'ai vu, mais c'est pas grave :)

**Comment by zemax** [comment]
C'est un dump de debug oublié. Je fais le ménage de suite.

**Comment by verovs** [comment]
réparé :)
