### ISSUE TITLE
Discussion : convertir les URLs en liens

### ISSUE THREAD

**Issue by Spone** [telabotanica/naturadapt#181]
On a un exemple dans la réponse ici : https://naturadapt.com/groups/plateforme-web/discussions/35c92d3d-2738-48f1-ac8f-bf2d70ddb98a

ce serait top que l'URL soit automatiquement convertie en lien.

**Comment by Spone** [comment]
@zemax tu peux faire ça stp ?

**Comment by zemax** [comment]
Sur 83919259fbb8b5c4430c22492812bf9dfdeb59c2 j'ai rajouté un post-process en JS qui converti les URLs non-liens en lien.
J'ai préféré JS pour ne pas risquer de casser la donnée et pouvoir revenir en arrière si le parsing n'était pas satisfaisant. En plus je peux me servir du DOM du coup, qui est à mon avis plus fiable qu'un parsing de tout le text en PHP.

**Comment by zemax** [comment]
Mon test est ici : https://naturadapt.etamin.studio/groups/les-discuteurs/discussions/b49996f6-230d-461d-b5d4-7708d8088a63

**Comment by Spone** [comment]
Top !
