### ISSUE TITLE
Avatars et noms cliquables > profil

### ISSUE THREAD

**Issue by Spone** [telabotanica/naturadapt#182]
Dans les discussions, pourrait-on rendre les avatars et les noms cliquables pour visiter le profil de l'utilisateur ?

**Comment by Spone** [comment]
@zemax tu peux faire ça stp ?

**Comment by zemax** [comment]
Ok c'est rajouté sur 9b6a08954f1d46dc8becebafcef521cfe99018b1

**Comment by Spone** [comment]
Merci :)
