### ISSUE TITLE
Modération / validation d'un groupe

### ISSUE THREAD

**Issue by Spone** [telabotanica/naturadapt#196]
Quand un nouveau groupe est crée, il ne s'affichera pas directement sur le site.
Il est placé dans une file d'attente de modération.

Les admins de la plateforme reçoivent alors une notification par e-mail avec un lien vers un formulaire leur permettant d'accepter ou refuser la mise en ligne.

**Comment by Spone** [comment]
> Cela implique de définir comment nommer un compte RNF en admin

Comme on l'avait envisagé initialement, on considère que les admins du groupe "Communauté" (qui est le groupe "par défaut") sont les admins de la plateforme. Ce serait donc à eux que serait envoyé le mail de notification.

**Comment by chikencheesenaan** [comment]
Comme discuter avec @Spone on penser mettre les groupes en attente de validation en premier, avant les groupes déjà valider pour les admins. Comme ça s'ils n'ont pas ouvert le mail de demande, ils peuvent voir les groupes en attente et les validés directement sans repasser par les mails. 

Lorsqu'on clique sur un groupe, on se retrouve sur la page d'activation qui reprend la page de demande d'un groupe privé en remplacent les boutons de demande d'inscription par les boutons pour accepter/refuser le groupe

Lien Xd : https://xd.adobe.com/view/44d8ac11-334c-454a-9144-95e9114c709d-118b/

**Comment by verovs** [comment]
voir si on peut en profiter pour intégrer #117 ^^

**Comment by Spone** [comment]
Il faut également modifier le message affiché lors de la confirmation de création d'un groupe, indiquant "Votre groupe a bien été créé, il est en cours de validation par un administrateur."

**Comment by ya-web** [comment]
est-ce que les utilisateurs peuvent voir leurs groupes en attente de validation (sans pouvoir les valider bien sûr :smile: )

**Comment by Spone** [comment]
> est-ce que les utilisateurs peuvent voir leurs groupes en attente de validation (sans pouvoir les valider bien sûr smile )

Oui ça peut être pas mal, sur ce principe là :

![image](https://user-images.githubusercontent.com/38524/96697834-a6387880-138c-11eb-92c4-9f8aab9f7164.png)

mais avec comme titre "Vos groupes en attente de validation"

**Comment by ya-web** [comment]
Il y a une raison pour qu'il y ait un moteur de recherche et que le titre des groupes qui ne sont pas à activer soit `Vos groupes `?
On liste bien tous les groupes? Sinon quelle est l'url de cette page c'est pas [/groups](url) ?

**Comment by verovs** [comment]
lorsque je clique sur le lien envoyé par mail j'arrive :  
![Capture d’écran de 2020-10-26 11-12-23](https://user-images.githubusercontent.com/22638189/97160403-964dd980-177c-11eb-91f6-c8615d5ed827.png)

Il faudrait, si possible, que j'ai accés sur cet écran aux description/présentation du groupe pour savoir de quoi il parle

**Comment by verovs** [comment]
Si je clique sur l'avatar du créateur de groupe > devrait m'envoyer sur /members ( https://naturadapt.etamin.studio/groups/lagunes/members )
notif fail avec encoche verte
![Capture d’écran de 2020-10-26 11-20-21](https://user-images.githubusercontent.com/22638189/97160875-458ab080-177d-11eb-8ae5-a2f6c10c8ce0.png)
J'aurai besoin de pouvoir accéder au profil du créateur pour pouvoir le contacter par mail si je veux des précisions  sur son groupe

**Comment by ya-web** [comment]
ok, pas de souci, j'avais fait ça, puis je me suis apperçu que ça n'y était pas sur la maquette

**Comment by verovs** [comment]
Lorque je clique sur "Refuser la création" 
ce lien action : 
https://naturadapt.etamin.studio/groups/activate/groupe-pas-acceptable/action/0

je tombe sur un forbiden

![Capture d’écran de 2020-10-26 12-22-55](https://user-images.githubusercontent.com/22638189/97166832-2d6b5f00-1786-11eb-9c98-c8e7dadec7e1.png)

**Comment by verovs** [comment]
pas très grave, à modifier qd on pourra :   
Dans le mail reçu pour m'informer de l'acceptation de mon groupe
![Capture d’écran de 2020-10-26 12-31-46](https://user-images.githubusercontent.com/22638189/97167785-b1721680-1787-11eb-975e-f7398ac499d9.png)

- Ily a un point après le nom du groupe
- le titre du mail pourrait être Votre groupe Natur'Adapt est accepté

**Comment by ya-web** [comment]
> Si je clique sur l'avatar du créateur de groupe > devrait m'envoyer sur /members ( https://naturadapt.etamin.studio/groups/lagunes/members )
> notif fail avec encoche verte

Qu'on soit bien d'accord ça signifie que les admin du groupe community on accès aux members de groupes privés ou pas?

**Comment by verovs** [comment]
Si on dit que admin communauté = admin plateforme alors ils ont accès à tout. 
actuellement sur la prod,  je suis admin dans la base de données,j'ai beau ne pas être ds les groupes privés je peux tout voir dans tous les groupes et tout faire, comme valider les membres en attente, éditer les pages, modifier les statuts des membres (= nommer admin du groupe ou retrograder)

**Comment by Spone** [comment]
> Qu'on soit bien d'accord ça signifie que les admin du groupe community on accès aux members de groupes privés ou pas?

J'aurais tendance à dire qu'en l'état actuel, non, car il n'apparaissent pas comme membres des groupes privés qu'ils n'ont pas rejoint. Ce serait donc bizarre qu'ils y aient accès.

**Comment by verovs** [comment]
ben si c'est les admins plateforme alors il faudrait ?

**Comment by Spone** [comment]
Mais dans la pratique, oui, il faut bien des super admins qui puissent gérer l'ensemble de la plateforme. A eux de rejoindre les groupes dans lesquels ils souhaitent effectivement participer (pour éviter d'avoir des contributions d'admin dans les groupes dont ils ne sont pas membres).

**Comment by verovs** [comment]
ha oui pour les contributions ! Je ferai un petit mémo pour les filles RNF pour leur expliquer

**Comment by ya-web** [comment]
Donc en attendant, je donne les mêmes droits aux admins de communauté **vis à vis des groupes** que les admins de la plateforme ou pas?

**Comment by Spone** [comment]
> Donc en attendant, je donne les mêmes droits aux admins de "communauté" **vis à vis des groupes** que les admins de la plateforme ou pas?

Ah ce sont deux concepts séparés actuellement "admin de la communauté" et "admin de la plateforme" ?

**Comment by ya-web** [comment]
admin de la plateforme pour moi ce sont utilisateurs (pas forcément dans un groupe) qui ont un rôle admin, les admins du groupe communauté on vient de leur donner la possibilité de modérer les autres groupes jusque là c'est tout, ils ne sont pas forcément admin de la plateforme

**Comment by verovs** [comment]
pour l'instant ça existait pas tel quel, je suis juste admin en bdd, on avait rien fait de plus
là l'idée était du coup de mettre admin plateforme les admins de communauté, même au delà des groupes, si ce sont eux qui sont sensé être admin & avoir les moderate . sinon on peut juste mettre Sandra  et Christine en admin plateforme en bdd ça va me va aussi

**Comment by ya-web** [comment]
#213

**Comment by verovs** [comment]
hé j'avais pas fait de retour ici, c'est tout bon :)
