### ISSUE TITLE
Affichage des vidéos

### ISSUE THREAD

**Issue by verovs** [telabotanica/naturadapt#197]
CKEditor permet d'intégrer des vidéos mais elles ne s'affichent pas (tout type de contenu et discussion)

Il faut donc afficher : 
- [x]  le lecteur vidéos quand c'est possible #211 
- [ ] un lien dans les autres cas (notifications mails)

**Comment by Spone** [comment]
Elles ne s'affichent pas dans l'éditeur ou sur la page une fois publié ?

Tu peux me faire un exemple sur l'environnement de staging ? Merci !

**Comment by Spone** [comment]
Related: #83

**Comment by verovs** [comment]
c'est une fois la page /discussion / actu / publiée  :
https://naturadapt.etamin.studio/groups/communaute/articles/actu-video-cool 
alors que si tu fais modifier tu vois tjs bien  la vidéo

![Capture d’écran de 2020-10-09 17-35-16](https://user-images.githubusercontent.com/22638189/95602878-d9f2d480-0a55-11eb-9ae2-331ea0e43dd8.png)

**Comment by verovs** [comment]
doc : https://ckeditor.com/docs/ckeditor5/latest/api/media-embed.html
https://ckeditor.com/docs/ckeditor5/latest/features/media-embed.html > ça c'est ce qu'on a
https://github.com/ckeditor/ckeditor5/search?q=media-embed

**Comment by kstefanini** [comment]
Il faut un script JS qui remplace ça
`<figure class="media"><oembed url="https://vimeo.com/338748780/8b52b04975"></oembed></figure>`
Par ça
`<iframe src="https://player.vimeo.com/video/338748780" width="640" height="360" frameborder="0" allow="fullscreen" allowfullscreen></iframe>`
(idem pour Youtube)

Donc en gros ça cherche les oembed, si une regexp détecte Vimeo ou Youtube (ou d'autres même si on veut) alors on prend l'identifiant de la vidéo et l'applique dans un template d'iframe et on remplace

**Comment by ya-web** [comment]
#211

**Comment by verovs** [comment]
Les vidéos s'affichent bien ! 
Mais elles sont en panormama 976x360

https://naturadapt.etamin.studio/groups/communaute/articles/actu-video-cool
https://naturadapt.etamin.studio/groups/communaute/articles/videossssss

![Capture d’écran de 2020-10-26 11-34-47](https://user-images.githubusercontent.com/22638189/97162409-779d1200-177f-11eb-9172-ffd385a1c549.png)

**Comment by verovs** [comment]
dans les discussions par contre  il n'y a tjs pas le lien de la vidéo
![Capture d’écran de 2020-10-26 11-41-43](https://user-images.githubusercontent.com/22638189/97163100-66a0d080-1780-11eb-9b5a-67075a90ed79.png)

**Comment by kstefanini** [comment]
C'est normal, rien n'a été fait pour les vidéos s'affichent dans les mails de notification.

**Comment by verovs** [comment]
Je ne veux pas forcement qu'elles s'affichent, mais au moins qu'elles apparaissent en lien.  On a eu des utilisateurs qui ont fait ça déjà.

**Comment by kstefanini** [comment]
Ok j'ai édité le ticket pour préciser.

> "On a eu des utilisateurs qui ont fait ça déjà."
Peux-tu préciser ce que tu veux dire par là ?

**Comment by verovs** [comment]
des utilisateurs ont voulu envoyer une vidéo youtube via les discussions
le lien/la vidéo n'est évidemment pas apparu dans les mails.
pour partager une vidéos ds cet endroit tu as 2 possibilités:
1) tu fais un embed pour mettre ta vidéo, et donc ça ne fonctionnait pas, logique, les vidéos ne marchaient pas (en front) et pas de lien dans le mail
2)  tu copie colle simplement un lien youtube dans un msg dans l'espace discussion > en fait  il se transforme automatiquement en embed video et tu repars au problème 1)
résultat : ça ne marche pas plus.
solution  qu'on avait trouvé : tu copies plusieurs fois ton lien youtube jusqu'à ce que ça soit un lien et pas en embed. 
cependant désormais les vidéos marchent en front donc ce serait bien qu'on affiche leur lien dans le mail, les utilisateurs ne vont pas penser que ça ne marche pas

**Comment by kstefanini** [comment]
Pour afficher un lien youtube au lieu du lecteur il suffit de faire ctrl + z pour annuler le remplacement automatique du lien youtube par le oembed par CKEditor

**Comment by verovs** [comment]
les vifdéos s'affichent désormais dans le contenu mais elles ne s'&affichent plus dans ckeditor
juste un grand carré blanc :(
les utilisateurs ne vont jamais comprendre qu'elles s'afficheront
![Capture d’écran de 2020-11-19 13-07-10](https://user-images.githubusercontent.com/22638189/99664310-49ea7680-2a68-11eb-970a-6a92b9283e18.png)

![Capture d’écran de 2020-11-19 13-07-31](https://user-images.githubusercontent.com/22638189/99664434-73a39d80-2a68-11eb-935c-3757fc4c2798.png)

https://naturadapt.etamin.studio/groups/communaute/articles/videossssss/
https://naturadapt.etamin.studio/groups/communaute/articles/videossssss/edit

**Comment by verovs** [comment]
parfait

**Comment by Spone** [comment]
Histoire de garder un lien vers la PR qui a corrigé le bug : #234
