### ISSUE TITLE
Matrice des droits

### ISSUE THREAD

**Issue by Spone** [telabotanica/naturadapt#2]
Action      | Visiteur      | Membre    | Administrateur  
------------ | ------------- | ------------- | -------------
S'inscrire | ✓ | |
Créer un groupe | | ✓ | ✓ 
Rejoindre un groupe public | | ✓ | ✓ 
Rejoindre un groupe privé | | ✓ (après modération) | ✓ 
Voir le contenu d'un groupe public | ✓ | ✓ | ✓ 
Voir le contenu d'un groupe privé | | ✓ (si membre) | ✓ 
Créer une discussion | | ✓ | ✓ 
Répondre à une discussion | | ✓ | ✓ 
Supprimer son propre compte utilisateur | | ✓ | ✓ 
Désactiver un utilisateur | | | ✓ 

(à compléter au fur et à mesure)

**Comment by zemax** [comment]
Top.
Je suis d'accord avec l'idée des liens supplémentaires "admin" sur les
contenus plutôt qu'un backoffice séparé, au moins tant qu'on n'en a pas le
besoin.

Le mar. 5 févr. 2019 à 15:10, Hans Lemuet <notifications@github.com> a
écrit :

**Comment by zemax** [comment]
Action                               | Visiteur | Non-Membre | Membre | Admin / Propriétaire
------------------------------------ | -------- | ---------- | ------ | --------------------
S'identifier                         | ✓        |            |        | 
S'inscrire                           | ✓        |            |        | 
*Supprimer son propre compte*        |          | ✓          | ✓      | ✓ 
Créer un groupe                      |          | ✓          |        | 
Voir le contenu d'un groupe public   | ✓        | ✓          | ✓      | ✓ 
Voir le contenu d'un groupe privé    |          |            | ✓      | ✓ 
Rejoindre un groupe public           |          | ✓          |        | 
Demander à rejoindre un groupe privé |          | ✓          |        |
Approuver une demande d'inscription  |          |            |        | ✓
Modifier un groupe privé ou public   |          |            | ✓      | ✓ 
Rendre administrateur un utilisateur |          |            |        | ✓ 
Bannir du groupe un utilisateur      |          |            |        | ✓ 
Créer une page                       |          |            | ✓      | ✓ 
Modifier une page non-verrouillée    |          |            | ✓      | ✓
Modifier une page verrouillée        |          |            |        | ✓
Déposer un document                  |          |            | ✓      | ✓ 
Supprimer un document                |          |            |        | ✓

**Comment by Spone** [comment]
Quelle est la distinction entre "Non-Membre" et "Membre" ? C'est à l'échelle d'un groupe ?

**Comment by zemax** [comment]
Oui, la plupart des droits de ce tableau sont relatifs à un groupe donné.
Du coup c'est pour différencier une personne non-identifée, une personne identifiée mais pas encore membre, une personne membre du groupe et une personne administratrice du groupe.
Il y a aussi ceux qui sont administrateurs au niveau de la plateforme, mais ceux là ont de toute façon tous les droits.
