### ISSUE TITLE
Recherche 

### ISSUE THREAD

**Issue by verovs** [telabotanica/naturadapt#223]
Le gros point manquant
Un MdR (moteur de recherche) full text sur tout et prenant en compte les droits des uers (: si je suis dans le groupe privé A je vois ses infos/pages/docs etc, mais je ne les voit pas si je n'en fais pas partie)
des MdR sur chaque appli d'un groupe
Un MdR sur la home d'un groupe

**Comment by verovs** [comment]
Retour utilisateur spécifiques :  

Recherche Annuaire général
:

-  ajouter la possibilité de trier par localisation dans l'annuaire  (si on veut créer un groupe sur un territoire en particulier, ça facilitera la démarche...)
- Est-ce qu'il est possible de trier par groupe dans l'annuaire ? (exemple, si on veut créer un groupe thématique mais par localité, ça facilitera la démarche..)
 = pouvoir voir , sans aller dans les groupes, qui fait partie du groupe A & B publics

Solution temporaire :  
 mettre en place à défaut du full txt elastic search une requete sur localité et groupes publics

Solution meilleure : déployer du full txt +  rechercher dans les groupes

**Comment by valentindb** [comment]
Voici les maquettes pour les résultats de recherche : 
https://xd.adobe.com/view/2bb869e8-92fd-41e3-8923-7d8d1f36a4e7-7eeb/

3 barres de recherche : 
-    Dans la page de liste des groupes (filtre les cartes de groupes affichés - page 3)
-    Dans le header (recherche dans tout, affiche la page de résultats avec les filtres détaillés plus haut - page 1 ou 2)
-    Dans la page d'accueil d'un groupe (recherche dans le groupe, affiche la page de résultats avec les filtres détaillés plus haut et le filtre correspondant au groupe pré-coché - variante de la page 1 ou 2)

**Comment by verovs** [comment]
Top ! (on est d'accord par contre que les pages 1 & 2 se sont les mêmes ? ^^)
