### ISSUE TITLE
nav principale ajouter item actualités

### ISSUE THREAD

**Issue by verovs** [telabotanica/naturadapt#230]
envoyer sur actualités du groupe communauté
ajouter cet item après ressources

**Comment by verovs** [comment]
faire des variables comme ici : https://github.com/telabotanica/naturadapt/commit/d3889e44d1a531709285273ed8bc72e208300c96

**Comment by kstefanini** [comment]
Fait ici : https://github.com/telabotanica/naturadapt/pull/247
