### ISSUE TITLE
Style tile

### ISSUE THREAD

**Issue by Spone** [telabotanica/naturadapt#24]
- Logo
- Typo(s)
- Couleurs standard

**Comment by chikencheesenaan** [comment]
**Style Guide :** https://xd.adobe.com/spec/31fcd019-7a9b-4eca-41ea-6db260edc0c9-47cd/screen/5e0c6e9e-23e3-40bc-9877-82f72f6d75bf/Web-1366-1/

**Font :** https://fonts.google.com/specimen/Open+Sans
