### ISSUE TITLE
Forcer HTTPS

### ISSUE THREAD

**Issue by Spone** [telabotanica/naturadapt#25]
voir https://www.clever-cloud.com/doc/php/php-apps/#force-https-traffic

**Comment by zemax** [comment]
C'est embetant de mettre ça dans le htaccess, je vais mettre ca dans une variable d'environnement (cf https://symfony.com/doc/current/security/force_https.html)

**Comment by Spone** [comment]
Ok ça me va. J'ai vu que tu as créé la variable d'environnement sur Clever Cloud. Petit souci de boucle de redirection pour le moment je crois...

**Comment by Spone** [comment]
C'est peut-être lié à leur config de `DirectorySlash` ?

**Comment by zemax** [comment]
Je pense que c'est du au HTTPS qui passe par un proxy
Je rajoute une var pour tester ça cf
https://symfony.com/doc/current/deployment/proxies.html

Le lun. 25 mars 2019 à 19:03, Hans Lemuet <notifications@github.com> a
écrit :

**Comment by zemax** [comment]
Ok ça fonctionne.
J'ai rajouté une var ```SECURE_SCHEME=https``` pour forcer le https
Ainsi qu'une var ```TRUST_ALL=1``` pour gérer le proxy
