### ISSUE TITLE
Mettre en place l'envoi d'e-mails

### ISSUE THREAD

**Issue by Spone** [telabotanica/naturadapt#29]
Nous utiliserons https://postmarkapp.com pour l'envoi (et plus tard la réception) d'e-mails "transactionnels" (= tout sauf les newsletters).

Voici les infos pour la mise en place de leur API au sein de l'application : https://github.com/wildbit/postmark-php/wiki/Getting-Started

Je te communiquerai les identifiants à utiliser.

**Comment by Spone** [comment]
J'ai créé les variables d'environnement `POSTMARK_SERVER_TOKEN` et `POSTMARK_SENDER` sur le serveur Clever Cloud.

**Comment by zemax** [comment]
C'est en place.
Je ne suis pas arrivé à rendre le choix SMTP vs Postmark configurable uniquement avec des variables d'environnement, il faut éditer le fichier de config de swiftmailer (config/packages/swiftmailer.yaml) pour choisir Config classique ou Transport par Postmark
