### ISSUE TITLE
Indexer les pages

### ISSUE THREAD

**Issue by Spone** [telabotanica/naturadapt#294]
Indexer toutes les pages de la plateforme, avec les champs suivants :

- `id` ID global (autoincrémenté)
- `usergroup_id` ID du groupe où se trouve la page
- `content_type` Type de contenu : `Page`
- `content_id` ID du contenu (= ID de la page)
- `content_title` : Titre du contenu (= `title` de la page)
- `body` Texte : `body` de la page (stripper le HTML)
- `url` URL absolue de la page (sans le domaine), par exemple `/groups/notre-bibliotheque/pages/analyse-de-la-vulnerabilite---les-activites-socio-economiques`
- `created_at`
- `edited_at`

**Comment by verovs** [comment]
question : t'indexes pas l'user ?
