### ISSUE TITLE
Ajouter un champ de recherche sur la page d'accueil d'un groupe

### ISSUE THREAD

**Issue by Spone** [telabotanica/naturadapt#296]
![image](https://user-images.githubusercontent.com/38524/138255583-8a523027-bbde-41b9-8232-5d8067aad2e9.png)

Maquette inspectable : https://xd.adobe.com/view/2bb869e8-92fd-41e3-8923-7d8d1f36a4e7-7eeb/screen/7b2fafff-07a2-4024-a0d2-72998656dd3e/specs/

L'idée est d'avoir un champ de recherche sur la page d'accueil de chaque groupe.

- La recherche renvoie sur la #297 avec par défaut le #298 correspondant activé.

**Comment by valentindb** [comment]
Le lien XD : https://xd.adobe.com/view/2bb869e8-92fd-41e3-8923-7d8d1f36a4e7-7eeb/screen/7b2fafff-07a2-4024-a0d2-72998656dd3e/
