### ISSUE TITLE
Page de résultats de recherche globale

### ISSUE THREAD

**Issue by Spone** [telabotanica/naturadapt#297]
Maquette inspectable : https://xd.adobe.com/view/2bb869e8-92fd-41e3-8923-7d8d1f36a4e7-7eeb/specs/

- Prévoir une pagination des résultats (même design qu'en bas de [cette page](https://naturadapt.com/groups/communaute/members))

## Évolutions

- Rafraîchissement des résultats instantané quand on active un filtre ou qu'on change une lettre dans le champ de recherche

**Comment by valentindb** [comment]
Tu as raison @Spone , j'ai masqué le champ dans la barre de nav pour ces pages (liens XD à jour)
