### ISSUE TITLE
Réglages du fuzzy search, ou incompréhension de résultats

### ISSUE THREAD

**Issue by verovs** [telabotanica/naturadapt#316]
Sur le stagging,il y a une majorité de résultats qui semblent peu compréhensifs, il faudrait trouver des réglages/paramètres en plus  à notre fuzzysearch

Sans être connectée : 
https://naturadapt.etamin.studio/search?form%5Bsearch_texts%5D%5Bquery%5D=poulpe&form%5Bsearch_filters%5D%5Bgroups%5D=all

le premier résultat : https://naturadapt.etamin.studio/groups/un-nom-tres-long-pour-reproduire-le-comportement-logo-ovaleuuuuh/pages/corail
le mot qui semble s'apparenter le plus à poulpe est "pour" (déduction à coup de ctrl f mais y'a pt etre autre chose avec la fin du mot) , nb ce mot est aussi en nom de groupe mais on ne semble pas chercher dedans car sinon la totalité du contenu de ce groupe devrait apparaître dans ma recherche et ce n'est pas le cas)
le second résultat : https://naturadapt.etamin.studio/groups/un-nom-tres-long-pour-reproduire-le-comportement-logo-ovaleuuuuh/pages/hey
ici on trouve en auteur mimipoulpe et sa description "poulpologiste", mais normalement on ne cherche pas là dessus si je me rappelle bien (et si on cherche dessus alors on devrait me sortir tous les résultats de cette autrice ce qui n'est pas le cas) , idem le mot apparenté à poulpe est "pour"
3ème résultat : https://naturadapt.etamin.studio/groups/un-nom-tres-long-pour-reproduire-le-comportement-logo-ovaleuuuuh/discussions/ce2701e5-b14b-434a-adbd-b6026ba7c728
on y trouve une intervention de mimipoulpe, deux fois le mot "pour" (+ 1 autre fois pour le nom de groupe)

etc.

idem si je cherche "corail" https://naturadapt.etamin.studio/search?form%5Bsearch_texts%5D%5Bquery%5D=corail&form%5Bsearch_filters%5D%5Bgroups%5D=all
je trouve bien ma page corail :) , j'ai une page avec corallienne https://naturadapt.etamin.studio/groups/communaute/articles/les-atolls (top!) mais j'ai aussi cordialement

**Comment by verovs** [comment]
@Spone je veux bien ton avis là dessus, comment pourrait-on mieux paramétrer ça (enfin si t'as une idée, si ce n'est pas lié à la techno!)

**Comment by aschlegle** [comment]
- Pour le premier résultat, le mot qui matche avec "poulpe" est le mot "polype", qui apparaît 4 fois sur cette page. Ce résultat semble logique car la fuzzy_distance est de 2 (2lettres de changée par rapport au mot de base). Il n'apparaît pas surligné cependant, car on ne surligne que le mot de base (si poulpe apparaît, on le surligne). 
Pour éviter un résultat comme celui-ci, on peut faire passer la fuzzy_distance à 1(j'ai testé en local, c'est plus cohérent quand même).
- Pour les 2 autres résultats, j'ai revérifié et se sont seulement les champs 'title' et 'body' qui ont été indexés, donc ça doit être un mot qui ressemble à poulpe à 2 lettres prêts.

Les autres paramètre pour la fuzzy search sont: 
- fuzzy_prefix_length: nb de lettre au début du mot qui doivent absolument apparaître. Actuellement il est à 2.  
-fuzzy_max_expansions: Le nombre de match avant que la recherche ne stoppe. J'ai mis la valeur par défaut, càd 50

**Comment by verovs** [comment]
T'as fait des modifs et c'est bien mieux !
J'ai encore qques problèmes car maintenant c'est trop sévère :(   

Si je cherche "pastèque"  je ne vais pas tomber sur les résultats pasteque (sans accents)  :  
https://naturadapt.etamin.studio/search?form%5Bsearch_texts%5D%5Bquery%5D=pasteque&form%5Bsearch_filters%5D%5Bgroups%5D=all

Si je cherche pasteque, je ne vais pas tomber sur les résultats avec accents :  
https://naturadapt.etamin.studio/search?form%5Bsearch_texts%5D%5Bquery%5D=pasteque&form%5Bsearch_filters%5D%5Bgroups%5D=all


si je cherche pastéque ou pasteque ou pastèque
je ne vais pas tomber sur les résultats pastéque-a-chair-blalba- (ce sont des documents)
j'ai un doc ici : https://naturadapt.etamin.studio/groups/cephalopodes-benthiques-du-sous-ordre-incirrina/documents  
et le même ici https://naturadapt.etamin.studio/groups/plateforme-web/documents

**Comment by aschlegle** [comment]
> Si je cherche "pastèque" je ne vais pas tomber sur les résultats pasteque (sans accents) : https://naturadapt.etamin.studio/search?form%5Bsearch_texts%5D%5Bquery%5D=pasteque&form%5Bsearch_filters%5D%5Bgroups%5D=all
> 
> Si je cherche pasteque, je ne vais pas tomber sur les résultats avec accents : https://naturadapt.etamin.studio/search?form%5Bsearch_texts%5D%5Bquery%5D=pasteque&form%5Bsearch_filters%5D%5Bgroups%5D=all

Le souci venait du stemmer. En fait les accents n'étaient pas tolérés par l'ancien. A présent le nouveau stemmer est français donc c'est corrigé! Tu peux retester et me dire :)

**Comment by verovs** [comment]
Top ! en plus avec ton explication sur l'autre ticket "lagunee / laguneee" j'ai mieux compris

alors pour l'instant c'est pas encore déployé sur le stagging (même avec le deploy de 15h07)

https://naturadapt.etamin.studio/search?form%5Bsearch_texts%5D%5Bquery%5D=past%C3%A8que&form%5Bsearch_filters%5D%5Bgroups%5D=all    (le bon lien avec accent) sort 12
et sans accent en sort 5
https://naturadapt.etamin.studio/search?form%5Bsearch_texts%5D%5Bquery%5D=pasteque&form%5Bsearch_filters%5D%5Bgroups%5D=all

et ici j''ai mon ex d'item sans accent https://naturadapt.etamin.studio/groups/plateforme-web/pages/mentions-legales    qui sort pas dans les accents (je me le note ici pour ne pas l'oublier)

**Comment by aschlegle** [comment]
> si je cherche pastéque ou pasteque ou pastèque
> je ne vais pas tomber sur les résultats pastéque-a-chair-blalba- (ce sont des documents)
> j'ai un doc ici : https://naturadapt.etamin.studio/groups/cephalopodes-benthiques-du-sous-ordre-incirrina/documents
> et le même ici https://naturadapt.etamin.studio/groups/plateforme-web/documents

Ce résultat est normal. En fait seuls les espaces sont utilisés comme separator actuellement. Donc, "pastéque-a-chair-blalba" est considéré comme un seul mot et ne match pas. 
Je peux créer un tokenizer si c'est une priorité. Cela séparera les mots séparés par un tiret.

**Comment by verovs** [comment]
non c'est pas du tout prioritaire :)

**Comment by aschlegle** [comment]
> alors pour l'instant c'est pas encore déployé sur le stagging (même avec le deploy de 15h07)

Non c'est bien déployé !
Cependant il faut relancer la commande de création des index avec le nouveau stemmer :) @Spone

**Comment by aschlegle** [comment]
Ce que je peux encore changer c'est la fuzzy_distance. Je peux la passer à 2 si c'est trop restrictif dans tes tests

**Comment by verovs** [comment]
On reste comme ça c'est très bien :)   une fois que les accents passent ça sera parfait !

**Comment by aschlegle** [comment]
Cool! =)
