### ISSUE TITLE
Inconsistance de présentation des résultats

### ISSUE THREAD

**Issue by verovs** [telabotanica/naturadapt#317]
Basée sur : https://naturadapt.etamin.studio/search?form%5Bsearch_texts%5D%5Bquery%5D=poulpe&form%5Bsearch_filters%5D%5Bgroups%5D=all

Si je pars du principe que le mot trouvé est "pour" certains résultats approximatifs sont affichés en "..."  tandis que d'autres apparaissent en extraits. Je n'arrive pas à décrypter la logique. De plus certains résultats non liés à fuzzysearch ne sont pas mis en évidence

Les deux résultats pages apparaissent en (...)
Des discussions apparaissent en extrait et une autre non (alors qu'elle a aussi un pour)
![Capture d’écran de 2022-01-19 16-14-17](https://user-images.githubusercontent.com/22638189/150159469-de844f53-572c-4f6d-ac36-fde0c6aef8c3.png)

![Capture d’écran de 2022-01-19 16-15-43](https://user-images.githubusercontent.com/22638189/150159672-fc2555ea-47f8-49ec-8eb7-cab8104c0870.png)
lien discussion : https://naturadapt.etamin.studio/groups/cephalopodes-benthiques-du-sous-ordre-incirrina/discussions/9b3a9646-d9f4-45e1-ad06-d0b2669e3b85   (ctrl f "pour")

Idem pour des actualités, qui ont pour certaines des extraits mais pas toutes

![Capture d’écran de 2022-01-19 16-17-07](https://user-images.githubusercontent.com/22638189/150159881-2c5f6679-3378-4538-87e9-331ca6df8fd6.png)
lien actualité : https://naturadapt.etamin.studio/groups/plateforme-web/articles/les-cactus  (ctrl f "pour")

Les membres, en bas de liste, comportent le mot exact recherché, cependant celui-ci n'est pas en valeur (surligné en jaune et font italique comme sur d'autres résultats qui matchent à 100%)

![Capture d’écran de 2022-01-19 16-33-19](https://user-images.githubusercontent.com/22638189/150163189-eff45867-be43-4e02-8ad4-bb6818e36da9.png)

"poulpe" non valorisé

alors qu'ici avec un résultat qui matche cela donne ça (sur un autre type, page et non membres)  : 
![Capture d’écran de 2022-01-19 16-36-17](https://user-images.githubusercontent.com/22638189/150163632-f81e0f56-5ff4-4e59-9c97-97fda7521c65.png)

lien de la recherche pour visualiser :  https://naturadapt.etamin.studio/search?form%5Bsearch_texts%5D%5Bquery%5D=corail&form%5Bsearch_filters%5D%5Bgroups%5D=all  

Sur cette autre recherche : https://naturadapt.etamin.studio/search?form%5Bsearch_texts%5D%5Bquery%5D=titre&form%5Bsearch_filters%5D%5Bgroups%5D=all

deux actualités ont toutes les deux le mot "titre"  dans leur titre
![Capture d’écran de 2022-01-19 18-43-48](https://user-images.githubusercontent.com/22638189/150185380-cfde7fcb-cc4a-41e3-b6ed-552f32dcb722.png)

une apparaît avec la totalité de son contenu (qui est court ^^⁾ et qui ne contient pas le mot titre : 
Texte court lalala)
l'autre apparaît avec 4 points (sous entend un résultat en fuzzysearch ? cependant les seuls matchs que je trouve dans le texte sont des mots contenant "ti", cf #316 si c'est le cas )

**Comment by aschlegle** [comment]
- Concernant: https://naturadapt.etamin.studio/search?form%5Bsearch_texts%5D%5Bquery%5D=poulpe&form%5Bsearch_filters%5D%5Bgroups%5D=all
Alors en fait pour centrer le texte sur un mot j'utilise une fonction de TNTsearch. Si le texte en entrée est inférieur à 120char alors il est renvoyé tel quel. Sinon il est centré sur le premier match avec le mot (mot exact de départ, pas trouvé moyen de centrer sur le mot qui a matché lors de la recherche). Si il n'y a pas de match, ce qui est renvoyé c'est la chaîne '.....'. 
Pour la recherche sur les groupes j'ai actualisé ça (si pas de match dans le texte, j'affiche le texte plutôt que '.....'). Je peux faire la même chose ici. 
C'est la même chose pour les actualités (à chaque fois que cette fonction est appelée en fait).

- Pour le membre Mimi Poulpe, je n'ai pas appliqué la fonction de surlignage dessus. Mais c'est bien le mot Poulpe qui matche. 
Est ce que le design vous va déjà? (j'ai ajouté le nom de l'auteur mais peut être qu'on ne veut pas qu'il apparaîsse par exemple). @Spone notamment.

-Enfin pour le mot titre, c'est bien lui qui matche, et qui renvoie le résultat. Le body est long et aucun mot ne matche précisément avec la recherche "titre", donc le texte renvoyé est '.....'

**Comment by aschlegle** [comment]
Ce dernier commit permet de ne plus retourner les textes vides. 
Pour un texte long et sans match, on affiche le texte de base (et non ".....").

**Comment by verovs** [comment]
C'est top :)
