### ISSUE TITLE
MdR sur plusieurs termes : fonctionnement par OU à la place de ET

### ISSUE THREAD

**Issue by verovs** [telabotanica/naturadapt#318]
Comme le titre, il me semblait qu'on avait décidé de faire du ET
et ici cela donne du ou : https://naturadapt.etamin.studio/search?form%5Bsearch_texts%5D%5Bquery%5D=poulpe&form%5Bsearch_filters%5D%5Bgroups%5D=all&form%5Bsearch_texts%5D%5Bcurrent_tags%5D%5B%5D=titre

**Comment by aschlegle** [comment]
Je peux changer cela. Voici ce que ça change dans les résultats (avec la fuzzy_distance toujours à 2):
Avant:
![image](https://user-images.githubusercontent.com/64697723/150311685-f9ad8a16-befe-452d-abc1-9b38c2a643e6.png)
Après:
![image](https://user-images.githubusercontent.com/64697723/150311548-835a72b7-3835-4aa2-9e63-259fe15cb001.png)

**Comment by verovs** [comment]
top :)
