### ISSUE TITLE
[MdR] filtre groupe : enlever les tirets des noms de groupes / cassent le layout

### ISSUE THREAD

**Issue by verovs** [telabotanica/naturadapt#323]
Pas certaine que ce ne soit pas déjà pris en compte dans une PR mais au cas où
Pour la recherche par nom de groupe il faut "dé-kebabcasiser" (j'ai appris ce mot je veux le placer  poke @kstefanini ^^) le nom des groupes aussi bien dans l'affichage que dans l'autocompletion.

-> Cela devrait permettre qu'ils ne sortent plus du layout comme actuellement, cf.  

![Capture d’écran de 2022-01-20 10-43-05](https://user-images.githubusercontent.com/22638189/150319284-5ce0e59b-26aa-40f6-b894-0bd4653ebd4a.png)

**Comment by aschlegle** [comment]
Le kebab case n'y est pour rien, c'est un problème de style. 
Voici ce que l'affichage que je peux proposer:
![image](https://user-images.githubusercontent.com/64697723/150337756-9c5b3b5f-4f4b-4676-ad00-1a3981bd153f.png)
