### ISSUE TITLE
le filtre mes groupes fais renvoyer une 500 qd on n'est pas connecté

### ISSUE THREAD

**Issue by verovs** [telabotanica/naturadapt#327]
enfin d'après ce que je décrypte de l'erreur et comme on vient juste de le deployer en staging  #314 
![Capture d’écran de 2022-01-20 17-09-26](https://user-images.githubusercontent.com/22638189/150377041-c02982d8-10d6-4838-8b33-d72c42292dbc.png)

Une fois connectée pas de souci

**Comment by aschlegle** [comment]
Le problème devrait être réglé avec le fixe précédent

**Comment by verovs** [comment]
c'est ok !
