### ISSUE TITLE
Les items des groupes privés ressortent même sans en être membre

### ISSUE THREAD

**Issue by verovs** [telabotanica/naturadapt#336]
Je sais pas si c'est parce que ce n'est pas encore réglé mais je tombe sur des items privés en étant non loguée (donc ne faisant pas partie du groupe)

Affichage d'une discussion d'un groupe privé : 
https://naturadapt.etamin.studio/search?form%5Bsearch_texts%5D%5Bquery%5D=&form%5Bsearch_texts%5D%5Bcurrent_tags%5D%5B%5D=djhk

Affichage d'une actu ET d'une page du même groupe : 
https://naturadapt.etamin.studio/search?form%5Bsearch_texts%5D%5Bquery%5D=&form%5Bsearch_texts%5D%5Bcurrent_tags%5D%5B%5D=lagune

(Le doc nommé lagunee ne sort pas)

**Comment by aschlegle** [comment]
Sauf erreur de ma part, on n'avait pas abordé cette question des groupes privés dans ce cas là.
Dans l'état actuel des choses: 
- si l'on n'est pas connecté: afficher le contenu de tous les groupes indexés (public et privés)
- si l'on est connecté et avec "Tous les Groupes" coché: afficher le contenu de tous les groupes (publics et privés)

**Comment by aschlegle** [comment]
**Pour la deuxième recherche**
Le résultat est en accord avec ce qui est attendu. 
On a un match avec 2 éléments appartenant au groupe, ces 2 là s'affichent

**Comment by aschlegle** [comment]
Enfin si le doc ne s'affiche pas, c'est parce que son nom est 'laguneee' et non 'lagunee'
Avec la fuzzy_distance à 1, il ne ressort car luguneee diffère de 2 lettres.

**Comment by verovs** [comment]
Alors effectivement l'idée serait d'avoir :  

-   si l'on n'est pas connecté: afficher le contenu uniquement des groupes publics indexés
-   si l'on est connecté et avec "Tous les Groupes" coché: afficher le contenu de tous les groupes publics + des groupes privés auxquels je suis membre
- si l'on est connecté et avec "Mes Groupes" coché: afficher le contenu de tous les groupes dont je suis membre, peu importe leur statut

Après si ce n'est pas possible (car trop de temps) on pourrait pt être simplifier (je ne sais pas si c'est plus simple!) de faire : 
-   si l'on n'est pas connecté: afficher le contenu uniquement des groupes publics indexés
-   si l'on est connecté et avec "Tous les Groupes" coché: afficher le contenu de tous les groupes publics 
- si l'on est connecté et avec "Mes Groupes" coché: afficher le contenu de tous les groupes dont je suis membre, peu importe leur statut (si possible)

> en gros enlever les contenus des  groupes privés pour les 2 premiers cas et le garder pour le dernier (si faisable, si trop compliqué il est même préférable d'enlever les groupes privés là aussi je pense)

Le contenu des groupes privés n'est pas indexé (google et co) car  ils peuvent éventuellement être dédié à des actions de coordination et contenir des discussions "politiques / stratégiques/financières" et il vaut mieux éviter de retourner ces discussions et des fichiers tableur de budget 

On peut en discuter pour trouver quelle solution serait la plus facile :)

**Comment by aschlegle** [comment]
Comme ça je dirait que les 2 solutions ont le même coût. Je vais faire ça tout de suite

**Comment by aschlegle** [comment]
Avec ces changements:
- En hors connexion on n'affiche plus les infos de groupes privés dans les résultats de la recherche; 
- En connexion on affiche seulement les infos des groupes privés auxquels le membre courant appartient;
