### ISSUE TITLE
Changer texte bouton après demande d'inscription

### ISSUE THREAD

**Issue by Spone** [telabotanica/naturadapt#36]
Une fois que j'ai cliqué sur "Demande d'inscription", il faudrait changer le texte du bouton par "Inscription demandée" et le désactiver.

![image](https://user-images.githubusercontent.com/38524/57135445-b9771300-6da9-11e9-8fea-53f73c797fc0.png)

**Comment by zemax** [comment]
status "pending" ajouté sur le commit ae70ff67fbd22fd57ac543371b94ed72feee7cc5
