### ISSUE TITLE
Documenter l'ajout de "compétences"

### ISSUE THREAD

**Issue by Spone** [telabotanica/naturadapt#37]
Est-il possible de documenter dans le README ou dans un fichier Markdown à l'intérieur du projet, la manière d'ajouter des "compétences" au formulaire de profil ? Quels sont les fichiers à modifier ? Y a-t-il une manip particulière à faire ou est-ce qu'il suffit de redéployer ?

Je pense que ce sera une demande que l'on peut anticiper et si c'est documenté, je pourrai m'en charger directement :)

**Comment by zemax** [comment]
Rajouté sur le commit 1a1da4e99973cc625479dcb27cc33a8bc082cc0a
