### ISSUE TITLE
Admin : Impossible d'éditer le nom des menus (footer)

### ISSUE THREAD

**Issue by verovs** [telabotanica/naturadapt#384]
Sur l'interface d'admin #341 
Sur l'édition des menus

Il n'est pas possible de modifier les titres des menus, ils sont éditables, je peux les changer, par contre la modif n'est pas prise en compte lors de la sauvegarde. cela ne déclenche pas non plus d'erreur en console.
![Capture d’écran du 2023-01-17 17-18-53](https://user-images.githubusercontent.com/22638189/212953801-e34b1135-ae76-4aaa-a326-756a36f27d6f.png)

j'ai essayé des titres courts, avec ou sans majuscules, des titres sans caractères spécifiques (comme une apostrophe), des titres plus longs etc. Rien ne se passe, l'enregistrement de la modif ne fait que reloader le form.

Par contre je peux bien modifier les noms des items du menu, mettre des liens, même un mailto, changer l'ordre etc. ça fonctionne bien :)

**Comment by aschlegle** [comment]
Corrigé dans la PR #411
