### ISSUE TITLE
Gestion du code et repo, créer des nouvelles branches

### ISSUE THREAD

**Issue by verovs** [telabotanica/naturadapt#393]
voici ce que Killian a dit à ce sujet le 14/12 :  

si uniquement changement de style , tout garder sur repo NA

style généraliste + feuille de style alternatives qui viennent surcharger feuille de style générale
rendre feuille de style configurable  : dossier style NA
dossier style OFB

variable d’environnement avec le nom de la déclinaison de style intéressant + builder webpack qui se base sur cet env pour intégrer surcharge

plausible à passer en environnement
tout le reste à l’air d’etre déjà en environnement (bdd, nom plateforme, postmark etc)

si y’a des prod différentes (ex : NA améliorations admin pas encore en prod) faire des branches

**Comment by verovs** [comment]
On va avoir des prods (et des developp) différentes en fonctionnalités, pas que du style

**Comment by verovs** [comment]
@Spone ici pour savoir ce que t'en penses à l'occaz' , on créé deux branches, une na, une poll ?  Comment on gère les main et developp ? 
NA va apporter des modifs (admin, une carto) qui ne seront pas sur poll, poll aura aussi des champs de profil différents et son style
HS : NA va aussi changer de serveur (transfert en avril, faudra dé-lier clever cloud à sa repo (pas sure que ça marche comme ça :P )
@arthur-tela dans la boucle, pour voir ce qui va arriver en février, j'ai doucement commencé à créer le projet sur github :)

**Comment by Spone** [comment]
À voir s'il ne vaut pas mieux carrément faire un fork. Pour vraiment isoler les projets, car ils seront déployés séparément. On en rediscutera !
