### ISSUE TITLE
Accueil non-connecté

### ISSUE THREAD

**Issue by Spone** [telabotanica/naturadapt#4]
https://xd.adobe.com/view/fadc33db-9c84-4133-6ae0-c1bd5539049f-8ced/?hints=off

- Présentation de la plateforme

- [x] remettre le contenu initial avec la mise en page spécifiée par Tela

**Comment by valentindb** [comment]
https://xd.adobe.com/view/da3ca5d6-7cd5-4769-586b-d484673d1fe3-ac0d/
