### ISSUE TITLE
Éditeur WYSIWYG

### ISSUE THREAD

**Issue by zemax** [telabotanica/naturadapt#40]
Des suggestions / souhaits pour le choix de l'éditeur WYSIWYG ? Il me semble que tu m'en avais cité un particulier ?

**Comment by Spone** [comment]
J'aime bien https://trix-editor.org

J'ai testé https://quilljs.com mais les performances sont assez mauvaises avec des longs contenus (ou plusieurs éditeurs par page)

Récemment j'ai découvert https://editorjs.io avec une approche "blocs" et un super éditeur de tableaux (!) mais le contenu est sauvegardé sous la forme d'un arbre JSON, qu'il faut ensuite interpréter lors du rendu.

Tu as des préférences toi ?

**Comment by zemax** [comment]
Pas vraiment de préférences. J'utilise CKEditor https://ckeditor.com/ classiquement avec Drupal.
Je me pose surtout la question des media images inclus dans le texte et comment les traiter.

**Comment by Spone** [comment]
CKEditor 5 a l'air top et en plus intègre l'édition collaborative : https://ckeditor.com/collaboration/ (potentiellement intéressant pour la suite !)

**Comment by Spone** [comment]
@zemax on part sur CKEditor donc ?

**Comment by zemax** [comment]
Je viens de rajouter CKEditor sur le formulaire de groupe et celui de page.
Je regarde pour gérer les uploads d'images via le wysiwyg.
