### ISSUE TITLE
le logo partenaires n'est plus modifiable (home) dans l'admin. 

### ISSUE THREAD

**Issue by verovs** [telabotanica/naturadapt#418]
le logo partenaires  (le gd bandeau) n'est plus modifiable dans l'admin. 
désormais le troisième champ texte apparaît en colonne, le logo rentrera pas
Il faudrait donc soit faire un autre encart texte, soit continuer de changer à la main quand / si / le logo change
#385

**Comment by verovs** [comment]
à voir si ça vaut le coup de corriger ou non, en tout cas c'est noté

**Comment by aschlegle** [comment]
Oui en effet les logos ne sont pas modifiables, mais c'est une volonté de départ je crois bien. 
Du moins c'est une possibilité qui' n'apparaît pas dans l'issue de départ #341 (et plus particulièrement elle n'apparaît pas ici: https://xd.adobe.com/view/3932b01e-0efe-46c7-9b3c-d3c322b737a6-6c61/screen/74d242ca-ba38-459c-9832-bdd2e77e04bc/ ). 

@verovs , ça pourrait être un oubli ou une volonté au départ?
