### ISSUE TITLE
les users admins affichés dans l'admin site ne sont pas les bons

### ISSUE THREAD

**Issue by verovs** [telabotanica/naturadapt#419]
C'est uniquement un problème d'affichage. Les anim de communauté ont bien accès à la page de modif  #380  est ok :)

les admin affichés ici : 
https://staging.naturadapt.com/administration/administrators
screen
![Capture d’écran du 2023-04-07 17-50-50](https://user-images.githubusercontent.com/22638189/230639164-50b5d512-cefd-4cf5-8968-0d2405bac044.png)

ne sont pas ceux qui ont une étoile sur le groupe communauté : 
https://staging.naturadapt.com/groups/communaute/members
![Capture d’écran du 2023-04-07 17-52-12](https://user-images.githubusercontent.com/22638189/230639287-6c890498-3ccf-48ce-a45f-6796d6b064eb.png)
exemple :

- image bleue est dans l'admin mais pas com
- Hans est juste dans com
- mimipoulpe est ds com
- photo N&Blanc est dans admin et pas communauté

Ils ont pt être un autre rôle en bdd ? je sais pas

**Comment by verovs** [comment]
en fait c'est tjs pas bon en affichage.
actuellement sur staging y'a que "jacques "  en admin.
![Capture d’écran du 2023-05-03 19-12-49](https://user-images.githubusercontent.com/22638189/235991204-0a48f7a2-03f0-450c-bcdd-d8183508ece3.png)

 ->  Il est tout à fait possible d'enlever l'affichage des profils des gens, 
simplement garder la phrase "Liste des administrateurs de la plateforme. Ajoutez, supprimez les rôles d'admin dans l''annuaire du groupe Communauté

**Comment by aschlegle** [comment]
Le problème venait que le groupe commununauté n'était l'id 1 partout. C'est réglé!

**Comment by verovs** [comment]
top !!! :)
