### ISSUE TITLE
Clarifier champ description & présentation

### ISSUE THREAD

**Issue by zemax** [telabotanica/naturadapt#42]
Quel champ est utilisé dans chacun des contextes d'affichage d'un groupe (liste des groupes, page récap du groupe, en savoir plus) ?

**Comment by Spone** [comment]
L'idée est bien d'avoir deux champs : description et présentation.

Ici c'est la description (tronquée si trop longue) :

![image](https://user-images.githubusercontent.com/38524/58965712-5239ed80-87b1-11e9-995b-23b7749b83c2.png)

Ici c'est la description :
![image](https://user-images.githubusercontent.com/38524/58965784-6d0c6200-87b1-11e9-83c7-766debd289ee.png)

En cliquant sur "En savoir plus" on déplie la présentation en dessous.
