### ISSUE TITLE
Exports des assets graphiques

### ISSUE THREAD

**Issue by Spone** [telabotanica/naturadapt#43]
- [x] logo
- [x] convertir toutes les icônes en SVG

![Logo_LifeNaturAdapt](https://user-images.githubusercontent.com/38524/58964535-5c5aec80-87af-11e9-944b-863414aa1d58.png)

**Comment by zemax** [comment]
Le logo on l'a pas en vecto ?

**Comment by Spone** [comment]
Non, à cause du dégradé on peut pas vraiment l'avoir facilement en SVG...

**Comment by Spone** [comment]
@zemax tu dois pouvoir récupérer toutes les icônes SVG depuis le lien XD de développement : https://xd.adobe.com/spec/c30945de-c5e2-4925-63c6-a6650c1092ec-b538/

**Comment by zemax** [comment]
Je ne trouve pas comment, je n'ai peut-être pas les droits suffisants ?

**Comment by chikencheesenaan** [comment]
https://send.firefox.com/download/5c76f78835ba85e0/#YEcPk3edcuqkqGmPwdgZHg
