### ISSUE TITLE
Erreur carto annuaire "Variable "all_members" does not exist."  lorsque je passe par l'url /members

### ISSUE THREAD

**Issue by verovs** [telabotanica/naturadapt#435]
Dans le menu haut on a un lien "raccourci" (une redir ? une config spéciale ? ) sous annuaire : https://staging.naturadapt.com/members  
cela permet d'avoir un lien plus cours que /communaute/annuaire  mais ça amène au même endroit

Si on clique là : https://staging.naturadapt.com/members
On a une erreur qui s'affiche : Variable "all_members" does not exist.. screen
![Capture d’écran du 2023-05-03 15-49-07](https://user-images.githubusercontent.com/22638189/235935452-2a4d3fc0-8932-4b8e-8d16-10dd40f566ae.png)

Par contre cette erreur n'existe pas du tout lorsque l'on passe par l'url  : https://staging.naturadapt.com/groups/communaute/members

**Comment by aschlegle** [comment]
La route est réparée!
