### ISSUE TITLE
(carto home) qd on n'est pas co on a des faux membres / et différence de "légende"

### ISSUE THREAD

**Issue by verovs** [telabotanica/naturadapt#438]
je suis sure tu l'as vu, mais quand on n'est pas connecté on a bcp bcp plus de membres qui ont une démarche d'adaptation :D  
pas co
![Capture d’écran du 2023-05-03 19-20-11](https://user-images.githubusercontent.com/22638189/235993006-717b81c3-0d8b-44d0-8ea5-dfcb93d91430.png)
co
![Capture d’écran du 2023-05-03 19-22-50](https://user-images.githubusercontent.com/22638189/235993743-e90065d7-d6ed-4796-94dc-bd5d95bb70c1.png)

Il y a aussi une différence d'affichage

Quand on est co et qu'on affiche la carte  qui présente le switch "montrer tous les users" en vert : cela affiche en fait les users  ayant une démarche d'adaptation (y'a juste moi  sur staging)
quand on switche ça affiche les users inscrits (on est 14)  (et on voit le nom du switch montrer les users avec une démarche d'adaptation"

quand on n'est pas co et qu'on passe sur la vue de tous les users du site, si on survolle les départements cela note  le "nbre de démarche d'adaptation"  : on en a 1 ds l'hérault (moi ?) un vers chez vous (alors que sur cette carte on mets juste les inscrits ? y'a pas d'histoire d'adaptation ?)

![Capture d’écran du 2023-05-03 19-34-38](https://user-images.githubusercontent.com/22638189/235998676-70e95bc3-1bb4-4e26-bb6f-4fc0d895d716.png)

quand on dézoome 
on a pleins de démarches d'adaptations , bien plus que de membres lol

![Capture d’écran du 2023-05-03 19-20-11](https://user-images.githubusercontent.com/22638189/235998783-08143176-f3aa-4cbe-bb46-fd60cd963d09.png)

 (pas certaine d'être claire  :S   )

**Comment by aschlegle** [comment]
Le problème vient du fait que, dans la bdd de staging,  beaucoup de gens n’ont pas leur ville de remplie. Mais, sur la bdd de prod, les gens ont des villes (avec ça j'obtiens une lattitude et une longitude et alors j'en déduis la région). 

Le fix est de ne compter que les personnes dont le champ "région" est rempli (pour l'Europe du moins, hors europe les gens n'ont pas de régions). 
Maintenant tous les nombres sont les même, peu importe le niveau de zoom.

**Comment by verovs** [comment]
d'acc c'est ok j'avais oublié les "faux users" aussi !  je fais juste un ticket pour changer une légende mais pas bloquant
