### ISSUE TITLE
Liste des groupes

### ISSUE THREAD

**Issue by Spone** [telabotanica/naturadapt#45]
Liste des groupes, non connecté : https://xd.adobe.com/view/fadc33db-9c84-4133-6ae0-c1bd5539049f-8ced/screen/f49c6822-659a-4162-aa1c-8d3ddb0eb2ea/Homepage-non-connect-e-?hints=off

Liste des groupes, connecté : https://xd.adobe.com/view/fadc33db-9c84-4133-6ae0-c1bd5539049f-8ced/screen/7e816a0c-497e-4cf5-b41a-bbb84849e82a/Homepage-non-connect-e-?hints=off

- Champ de recherche
- Liste des groupes (premier groupe = "général") basée sur des cartes groupe #19 

- [x] ajouter icône cadenas sur groupes privés
- [x] ajouter icône check sur les groupes dont on fait partie
- [x] changer les images sur les 3 premiers groupes + liseré blanc

![image](https://user-images.githubusercontent.com/38524/58959084-98d51b00-87a4-11e9-9925-684976e79097.png)

**Comment by Spone** [comment]
Remplacer le cadenas par une icône + explicite
![image](https://user-images.githubusercontent.com/38524/59773066-4409c800-92ad-11e9-8fb8-99233eb2fddb.png)

**Comment by chikencheesenaan** [comment]
🔄
