### ISSUE TITLE
Accueil connecté (tableau de bord)

### ISSUE THREAD

**Issue by Spone** [telabotanica/naturadapt#5]
https://xd.adobe.com/view/fadc33db-9c84-4133-6ae0-c1bd5539049f-8ced/screen/d27734fa-e22a-455b-bb70-aea20c5bc348/Homepage-Connect-?hints=off

- Message de bienvenue
- Prochaines étapes (pour l'onboarding)
- Champ de recherche
- Liste des groupes dont l'utilisateur est membre (inspiration)
- Fil d'actualités dans les groupes dont l'utilisateur est membre (inspiration dashboard Github ci-dessous)
- Liste des autres groupes basée sur des cartes groupe #19 

- [x] Retirer le bloc "profil" sous le bloc "suggestion"

## Inspiration

![image](https://user-images.githubusercontent.com/38524/52352044-2d648200-2a2c-11e9-8721-6bd07fb53809.png)

![image](https://user-images.githubusercontent.com/38524/52351954-fee6a700-2a2b-11e9-8e58-b4488e99ed13.png)

**Comment by valentindb** [comment]
https://xd.adobe.com/view/da3ca5d6-7cd5-4769-586b-d484673d1fe3-ac0d/screen/8c5031fb-8b04-4cb7-8983-85b73d1a9d08/Homepage-connect-1
