### ISSUE TITLE
Font-size des champs de saisie

### ISSUE THREAD

**Issue by zemax** [telabotanica/naturadapt#50]
Le corps des champs de saisie doit être au moins 16px pour éviter un zoom sur terminaux mobiles.

**Comment by chikencheesenaan** [comment]
Est-ce utile de mettre à jour les maquettes? 
Pour nous c'est ok de passer en 16px sur les medias queries mobile.

**Comment by zemax** [comment]
Je vais faire l'intégration comme ça, on verra directement si ça coince
