### ISSUE TITLE
Inscription : checkbox CGU

### ISSUE THREAD

**Issue by verovs** [telabotanica/naturadapt#56]
Il faudra améliorer l'interface inscription en ajoutant une case à cocher : J'accepte les conditions d'utilisations de la plateforme (+link sur la page mentions légales/CGU dont je n'ai pas encore l'URL )

Désolée d'y penser que maintenant. A faire après le déploiement de juin 2019.

**Comment by verovs** [comment]
Up ici !

la checkbox doit dire " :
J'accepte la charte Natur'Adapt " (? c'est pas très beau comme formulation)
"Je partage les valeurs de la charte Natur'Adapt ?

lien : https://naturadapt.com/groups/communaute/pages/charte-de-la-plateforme

**Comment by verovs** [comment]
+ les CGU sont ici : https://naturadapt.com/groups/plateforme-web/pages/mentions-legales

au milieu, il faudrait y faire une ancre ?

**Comment by Spone** [comment]
@verovs on l'ajoute sur ce formulaire on est d'accord ?

![image](https://user-images.githubusercontent.com/38524/96234689-0c428b80-0f9a-11eb-84b5-77d964ac714c.png)

@chikencheesenaan peux-tu faire une maquette ?

**Comment by verovs** [comment]
ouip sur le formulaire de création de compte :)

**Comment by chikencheesenaan** [comment]
Hop 😄  ! : https://xd.adobe.com/view/c200b17b-2145-4f17-9223-6f89cc908ecc-9753/

**Comment by verovs** [comment]
Parfait !

**Comment by ya-web** [comment]
Ok pour la case à cocher dans le formulaire d'inscription. Mais qu'est-ce qu'on fait pour les utilisateurs déjà inscrits?
Killian proposait de les redirriger vers une page formulaire d'acceptation des CGU + charte. Je pense que ça signifie la case à cocher et un bouton submit. Par contre quel serait les textes des titre, sous-titre et du bouton?
Je propose 
Titre: "Acceptez les CGU et la charte Natur'Adapt"
Sous-Titre: "Afin de pouvoir poursuivre votre expérience sur la plateforme Natur'Adapt vous devez accepter les conditions générales d'utilisation du site ansi que la charte de la plateforme."
Bouton: "Valider"

**Comment by Spone** [comment]
Oui ou alors pour les personnes déjà inscrites on leur envoie simplement un mail pour les informer de la mise en place des CGU ?

**Comment by kstefanini** [comment]
Désolé je vais répondre par une autre question :
Est-ce que les CGU doivent être explicitement acceptées ?
Ou bien sont-elles acceptées implicitement par chaque visiteur sur le site dès lors qu'il se connecte ?

**Comment by ya-web** [comment]
Que fait-on si l'utilisateur ignore le mail ou qu'il passe dans les spam. On peut le laisser utiliser la plateforme sans avoir de déclaration qu'il a lu les CGU?

**Comment by verovs** [comment]
L’utilisation du site Natur'Adapt https://naturadapt.com implique l’acceptation pleine et entière des conditions générales d’utilisation ci-après décrites. Ces conditions d’utilisation sont susceptibles d’être modifiées ou complétées à tout moment, les utilisateurs du Site sont donc invités à les consulter de manière régulière.
> tu acceptes  les cgu même si tu surfes en anonyme

Idéalement je suis d'accord avec vous, avec le combo mail +tu dois m'accepter ça à ta première visite ou alors tu supp ton compte
Après on est qd même sur des cgu légères ou l'info principale est qu'on utilise les données que tu renseignes ds ton profil pour les afficher sur l'annuaire.
Si on peut se permettre de faire le combo alors go,sinon tant pis, je vous laisse décider de ce qui est le mieux avec le tps imparti :/

**Comment by kstefanini** [comment]
Autant ignorer le cas particulier des gens qui étaient inscrits avant l'apparition de la checkbox, qui semble déjà inutile à la lecture des CGU.

**Comment by verovs** [comment]
Sur staging les liens sont inversés. lien mentions légales sur CGU et vice versa
![Capture d’écran de 2020-10-23 15-52-30](https://user-images.githubusercontent.com/22638189/97012189-e42dcc00-1547-11eb-91a8-6edd7a98900f.png)

**Comment by ya-web** [comment]
#212

**Comment by verovs** [comment]
ils sont dorénavant dans le bon ordre mais s'affichent en %slug%
(nb ce sont des pages qui n'existent pas sur le staging mais les groupes dont elles sont issues existent sur staging aussi)
https://naturadapt.etamin.studio/groups/%24%7BPLATEFORM_GROUP_SLUG%7D/pages/mentions-legales
![Capture d’écran de 2020-10-26 15-07-56](https://user-images.githubusercontent.com/22638189/97182883-5ea35980-179d-11eb-9252-1eb1e0974cb1.png)

**Comment by kstefanini** [comment]
Il faudrait créer les pages pour s'assurer que ça marche vraiment @verovs 
Normalement soit le lien s'affiche correctement soit il est caché 
Mais là il semble qui y ait un bug @ya-web

**Comment by verovs** [comment]
ok je fais ça!

**Comment by ya-web** [comment]
ça marche pas si les paramètres du .env sont correctement remplies?

**Comment by ya-web** [comment]
Le problème vient apparemment des variables d'environnement dans clever cloud. certaines variables font références à d'autres dans mon .env de symfony, le problème c'est qu'une fois dans clever cloud elle sont entourées de guillements du coup la référence marche plus, on est obligés de remplir chacune à la main au lieu de juste changer le paramètre de base voilà donc les liens remarchent mais, même si c'est mieux parcequ'on a tout en conf, bein faut tout remplir à la main une par une.

**Comment by ya-web** [comment]
Note pour plus tard: développer un vrai système pour les pages indispensables au site pour qu'elles soient indépendantes des groupes et pages de groupes

**Comment by verovs** [comment]
les liens sont ok maintenant !
