### ISSUE TITLE
Home : images manquantes

### ISSUE THREAD

**Issue by Spone** [telabotanica/naturadapt#57]
![image](https://user-images.githubusercontent.com/38524/59419653-a6edf180-8dcb-11e9-9da1-1ecaf937420c.png)

Des suggestions d'images à utiliser ?

**Comment by verovs** [comment]
Le texte est un peu changé et Alex il avait mis ceci : https://xd.adobe.com/view/fadc33db-9c84-4133-6ae0-c1bd5539049f-8ced/?hints=off
ça m'allait très bien mais je peux chercher d'autres imgs si tu préfères :)

**Comment by Spone** [comment]
Ok @zemax on part là-dessus :

![image](https://user-images.githubusercontent.com/38524/59420688-9dfe1f80-8dcd-11e9-90e0-14671a8caee1.png)

Normalement c'était dans l'export fait par @chikencheesenaan

**Comment by Spone** [comment]
S'il y a des modifs de texte @verovs tu peux les faire ici et faire une PR : https://github.com/telabotanica/naturadapt/blob/master/templates/pages/front.html.twig

**Comment by zemax** [comment]
Je les ai incluse en SVG directement dans le html
