### ISSUE TITLE
Page "A propos de la plateforme"

### ISSUE THREAD

**Issue by Spone** [telabotanica/naturadapt#58]
Il y a deux liens, dans le header :

![image](https://user-images.githubusercontent.com/38524/59420076-7c506880-8dcc-11e9-96f8-c173c17436e9.png)

et le footer :

![image](https://user-images.githubusercontent.com/38524/59420094-84100d00-8dcc-11e9-8152-319b6cb4b200.png)

Est-ce qu'il s'agit de la page d'accueil ou on veut avoir d'autres contenus, sur une autre page ?

**Comment by verovs** [comment]
Il est bien prévu de faire une page "A propos de la plateforme", qui décrira un peu plus son fonctionnement que la home ! C'est tout à fait dans mon TODO
J'imaginais que ce serait une page du groupe "communauté" qu'on choisirait de mettre en footer.

**Comment by verovs** [comment]
https://docs.google.com/document/d/19QMxx2v-oGSoKgyTTVMTiSXCq__Yh-GaPcF_z7wM0g8/edit?usp=sharing
( to do)
