### ISSUE TITLE
Pages des "Liens utiles"

### ISSUE THREAD

**Issue by Spone** [telabotanica/naturadapt#59]
Dans le footer :

![image](https://user-images.githubusercontent.com/38524/59420136-9b4efa80-8dcc-11e9-84c8-2eaf30d37592.png)

A-t-on les contenus de ces pages ? ou est-ce qu'on cache ces liens pour le moment ?

**Comment by verovs** [comment]
On cache ! par contre on pourrait placer la page ML/CGU ici
