### ISSUE TITLE
Accueil du groupe

### ISSUE THREAD

**Issue by Spone** [telabotanica/naturadapt#6]
Groupe public, non membre : https://xd.adobe.com/view/fadc33db-9c84-4133-6ae0-c1bd5539049f-8ced/screen/0975a46d-cac2-4bb7-b764-213469f6a2f5/Accueil-Groupe-Public-Connect-?hints=off
https://xd.adobe.com/view/fadc33db-9c84-4133-6ae0-c1bd5539049f-8ced/screen/86fec138-f386-4140-a9fe-27a162440ce2/Accueil-Groupe-Public-Connect-?hints=off

Groupe public, non membre, vide : https://xd.adobe.com/view/fadc33db-9c84-4133-6ae0-c1bd5539049f-8ced/screen/88ca23ed-4e1d-49f3-8b1b-31462c0fcbf5/Accueil-Groupe-Public-Connect-Empty-box?hints=off

Groupe Privée, non membre ; https://xd.adobe.com/view/fadc33db-9c84-4133-6ae0-c1bd5539049f-8ced/screen/cee67f3f-7475-4440-9093-b9a7a2ba7a79/Accueil-Groupe-Priv-Connect-?hints=off

Groupe, membre : https://xd.adobe.com/view/fadc33db-9c84-4133-6ae0-c1bd5539049f-8ced/screen/e6e57219-d008-429d-971b-2a24264f86cd/Accueil-Groupe-Public-Connect-?hints=off

Groupe membre administrateur : https://xd.adobe.com/view/fadc33db-9c84-4133-6ae0-c1bd5539049f-8ced/screen/51c30983-c686-42c3-b303-2d478f33e480/Accueil-Groupe-Public-Connect-Admin?hints=off

- Nom du groupe
- Cover
- Icône / logo
- Navigation dans les outils disponibles (onglets ou blocs ?)
- Description
- _Si non-connecté :_
  - _Si groupe public :_
    - Présentation
    - Fil d'actualité
  - _Si groupe privé :_
    - Présentation
- _Si connecté :_
  - _Si membre du groupe :_
    - Présentation (repliée)
    - Fil d'actualité
  - _Si non-membre du groupe : cf. si non-connecté_

## Inspirations

![image](https://user-images.githubusercontent.com/38524/52352779-8a146c80-2a2d-11e9-8ad6-efec655657c9.png)

- [x] modifier logo + cover

![image](https://user-images.githubusercontent.com/38524/58959250-f8cbc180-87a4-11e9-8bc4-f8439768ed4d.png)

- [ ] ajouter icône cadenas si groupe privé
- [x] ajouter étoile à côté des admins dans la liste
- [x] renommer page "Présentation" en "Historique" pour éviter la confusion
- [x] prévoir l'état vide de chaque bloc (bouton "Créer votre première page")

**Comment by valentindb** [comment]
Groupe public, user connecté : https://xd.adobe.com/view/da3ca5d6-7cd5-4769-586b-d484673d1fe3-ac0d/screen/889eb19b-cc91-4627-8636-89968d74e835/Accueil-Groupe-Public-Connect-

**Comment by valentindb** [comment]
Groupe privé, user connecté : https://xd.adobe.com/view/da3ca5d6-7cd5-4769-586b-d484673d1fe3-ac0d/screen/f42230d5-670b-473c-9eee-905fa4c1736f/Accueil-Groupe-Priv-Connect-

**Comment by valentindb** [comment]
Groupe privé, user connecté, inscrit au groupe : https://xd.adobe.com/view/da3ca5d6-7cd5-4769-586b-d484673d1fe3-ac0d/screen/cc25dac0-4131-4170-92a7-dff3da2f3ed0/Accueil-Groupe-Priv-Connect-Inscrit

**Comment by Spone** [comment]
@chikencheesenaan peut-être virer les deux blocs de la page du group du coup ? 

![image](https://user-images.githubusercontent.com/38524/58970531-e9a33e80-87b9-11e9-967e-7eafacaa1be8.png)
![image](https://user-images.githubusercontent.com/38524/58970540-edcf5c00-87b9-11e9-8116-89548b23d970.png)

et adapter ce bloc pour faire apparaître les utilisateurs en attente :

![image](https://user-images.githubusercontent.com/38524/58970577-00499580-87ba-11e9-8f7c-aca659a899e8.png)

**Comment by chikencheesenaan** [comment]
Done

**Comment by Spone** [comment]
Faudra juste mettre "0" au lieu des nombres :

![image](https://user-images.githubusercontent.com/38524/58973416-368a1380-87c0-11e9-9e78-d1d41a7c811f.png)

**Comment by chikencheesenaan** [comment]
yep c'est fait
