### ISSUE TITLE
Pages d'aide

### ISSUE THREAD

**Issue by Spone** [telabotanica/naturadapt#60]
Dans le footer :

![image](https://user-images.githubusercontent.com/38524/59420209-c3d6f480-8dcc-11e9-919c-ec62f40156a4.png)

A-t-on les contenus de ces pages ? ou est-ce qu'on cache ces liens pour le moment ?

Peut-être que le lien "Signaler un problème" peut être un `mailto:` vers une adresse e-mail `support@naturadapt.com` qui redirige vers nos boîtes mail ?

**Comment by verovs** [comment]
on a pas les contenus, on cache !
ok pour signaler un pb !

**Comment by verovs** [comment]
c'est fait depuis ^
