### ISSUE TITLE
mettre en place un analytics

### ISSUE THREAD

**Issue by verovs** [telabotanica/naturadapt#64]
Mise en place d'un suivi Analytics
Je peux surement le créer mais pas mettre le code

**Comment by verovs** [comment]
voici le code : 
`
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-142142612-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-142142612-1');
</script>`

**Comment by verovs** [comment]
Aller voir : ( Fathom ou Plausible, qui existent toutes les deux en self-hosted)
https://usefathom.com/
https://plausible.io/
et choisir le moins couteux en temps  (tarteaucitron ou eux)

**Comment by verovs** [comment]
piste : https://stackoverflow.com/questions/24257043/symfony2-adding-in-google-analytics-script-into-twig
apparemment faut juste modifier base.html.twig   et layout

**Comment by Spone** [comment]
Yep c'est juste à ajouter ici : https://github.com/telabotanica/naturadapt/blob/2d99d7d2c37a71a8631652ed0178616335816a3b/templates/base.html.twig#L25
