### ISSUE TITLE
Créer des mails & redirections

### ISSUE THREAD

**Issue by verovs** [telabotanica/naturadapt#67]
1 ) support@naturadapt.com
voir #60 

2) Ds les CGU j'ai noté
L’utilisateur peut à tout moment modifier ou supprimer son profil, détruisant ainsi les données personnelles y étant renseignées. Si l’Utilisateur n’arrive pas à effectuer la manipulation il peut demander au webmaster de faire l’opération pour lui en le contactant sur support@naturadapt.com
Ne faudrait-il pas imaginer un autre mail ? Peut-être que vous avez pas envie de gérer le cas 2 et n'avez pas besoin d'être en destination ^^

**Comment by Spone** [comment]
On mettrait qui comme destinataire(s) du support ? toi et moi ? comme ça ensuite on crée des issues ici si besoin ?

**Comment by verovs** [comment]
ouep !

**Comment by Spone** [comment]
Adresse support@naturadapt.com créée !
