### ISSUE TITLE
Annuaire

### ISSUE THREAD

**Issue by Spone** [telabotanica/naturadapt#7]
- Champ de recherche
- Filtres :
  - par date d'inscription au groupe (défaut)
  - par emplacement géographique
  - par ordre alphabétique
  - par compétence
  - ...
- Liste des membres sous forme de cartes membre #20, groupés selon le filtre choisi
- Carte géographique "filaire" si "par emplacement géographique" est sélectionné

- [x] Prévoir l'état de la page pour les admins, avec : des membres en attente en haut de la liste, des membres bannis en bas + enlever la flèche + ajouter une icône pour chaque action :

Si en attente : :heavy_check_mark: Accepter / :crossed_swords: Décliner / :no_entry_sign: Bannir
Si membre : :star: Promouvoir admin / Retirer du groupe / Bannir
Si bannir : Retirer le bannissement

+ filtre par statut (A valider, Membre, Banni)

**Comment by Spone** [comment]
Tu peux les espacer un peu plus ? Pour que la zone cliquable soit plus grande et plus facile à viser (au moment de l'inté on mettra du padding sur les boutons)

![image](https://user-images.githubusercontent.com/38524/58970695-2d964380-87ba-11e9-95a1-62f21403993b.png)

Pourquoi ne pas mettre décliner en rouge et l'engrenage en gris ?

**Comment by Spone** [comment]
Tu veux pas essayer un autre truc que de les griser ?

![image](https://user-images.githubusercontent.com/38524/58971216-3f2c1b00-87bb-11e9-9001-cd9220c23031.png)

Genre mettre un liseré vert à gauche ou autre. Le but est qu'ils ressortent visuellement, là ils sont plutôt un peu "masqués".

**Comment by chikencheesenaan** [comment]
Mieux comme ça ?

**Comment by Spone** [comment]
Oui c'est top ! Reste juste à corriger le filtre pour utiliser des radio buttons ou enlever l'item "Tout" (et ajouter Admin)

**Comment by chikencheesenaan** [comment]
Done

**Comment by Spone** [comment]
:+1:
