### ISSUE TITLE
Supprimer mon profil

### ISSUE THREAD

**Issue by verovs** [telabotanica/naturadapt#70]
Il faudrait ajouter une possibilité de supprimer son compte.

+ voir #71

**Comment by Spone** [comment]
Je propose que ce soit un bouton accessible depuis la page "Mes paramètres" (lien dans le menu déroulant au clic sur la photo de profil du header).

**Comment by chikencheesenaan** [comment]
Voici le lien de la page xd avec le nouveau bloc de suppression de compte : https://xd.adobe.com/view/c200b17b-2145-4f17-9223-6f89cc908ecc-9753/screen/53fc0427-b48c-4110-9720-ac6e20fbe38a/

**Comment by Spone** [comment]
Pour les textes, voilà ce que je suggère :+1: 

> ## Supprimer mon compte
> 
> Si vous supprimez votre compte, vos contributions sur la plateforme seront préservées mais votre nom n'apparaîtra plus. Vous ne serez plus listé dans l'annuaire des membres. Vous ne pourrez plus vous connecter.
> **Attention, cette opération est irréversible.**
>
> [Supprimer mon compte]

Ce serait bien d'avoir une confirmation qui ouvre une fenêtre native au clic sur le bouton "Supprimer mon compte" (avec la fonction [`confirm`](https://developer.mozilla.org/fr/docs/Web/API/Window/confirm)).

**Comment by verovs** [comment]
parfait ! Merci @chikencheesenaan & @Spone

**Comment by ya-web** [comment]
ça m'étonne qu'on ouvre pas une page formulaire de confirmation avec champ mot de passe et éventuellement email

**Comment by Spone** [comment]
@ya-web oui si vous voulez on peut ajouter une étape de vérification supplémentaire... mais ça fait pas mal de boulot en plus. Je me dis que comme c'est du soft-delete, en cas de hack ou de fausse manip on peut assez facilement rétablir le compte.

**Comment by verovs** [comment]
qd je clique sur supprimer > pop up  êtes vous sûr > oui > error 500![Capture d’écran de 2020-10-26 12-42-13](https://user-images.githubusercontent.com/22638189/97168488-d6b35480-1788-11eb-89f6-ef043d1119d9.png)

**Comment by verovs** [comment]
ok!
