### ISSUE TITLE
Gestion des contenus créés par profils supprimés

### ISSUE THREAD

**Issue by verovs** [telabotanica/naturadapt#71]
Les users peuvent /pourront : 
- écrire sur des pages 
- créer des groupes
- déposer des docs
- écrire sur des type forums

Une fois leur profil supprimé il faut décider de ce qui advient de tout ça. je serai pour tout garder et juste raccrocher à "ex user" 
-> J'afficherai "Utilisateur supprimé / ou "ancien utilisateur"
(milestone ds longtemps)

**Comment by Spone** [comment]
En effet, je reformule pour @zemax :

- [ ] Mettre en place un "soft delete" pour les utilisateurs : lorsqu'on supprime le compte toutes les infos personnelles sont supprimées, mais l'User reste en base avec un nom générique et un flag `deleted`.
- [ ] Lorsqu'on affiche un contenu associé à un utilisateur supprimé, afficher "Ancien utilisateur" à la place de son nom.

**Comment by zemax** [comment]
En leur associant un email type `deleted-<user-id>`pour garder la clé d'unicité par exemple ?

**Comment by Spone** [comment]
Oui parfait. D'ailleurs on pourrait utiliser "Ancien utilisateur n°`<user-id>`" pour pouvoir différencier les users dans une discussion où il y aurait plusieurs utilisateurs supprimés.

**Comment by Spone** [comment]
Oui parfait. D'ailleurs on pourrait utiliser "Ancien utilisateur n°`<user-id>`" pour pouvoir différencier les users dans une discussion où il y aurait plusieurs utilisateurs supprimés.

**Comment by chikencheesenaan** [comment]
Voici comment sera afficher l'utilisateur supprimer : 

<img width="545" alt="Capture d’écran 2020-10-09 à 11 00 37" src="https://user-images.githubusercontent.com/45854391/95564255-d2fc9f80-0a1e-11eb-8b7a-3ada7ff2e813.png">

L'avatar en svg : [Ancien utilisateur.svg.zip](https://github.com/telabotanica/naturadapt/files/5353710/Ancien.utilisateur.svg.zip)

**Comment by ya-web** [comment]
> En leur associant un email type `deleted-<user-id>`pour garder la clé d'unicité par exemple ?


> Oui parfait. D'ailleurs on pourrait utiliser "Ancien utilisateur n°`<user-id>`" pour pouvoir différencier les users dans une discussion où il y aurait plusieurs utilisateurs supprimés.

Ok mais si on est sur du "soft delete" , il s'agit d'un simple affichage (l'utilisateur a un flag `deleted` on affiche un "Ancien utilisateur n°`<user-id>`" et le mail `deleted-<user-id>` c'est ça? sachant que les infos perso ont été suprimées, si l'utilisateur reprend son compte à la suite d'une erreur il doit tout recommencer hormis nom et mot de passe

**Comment by Spone** [comment]
> si l'utilisateur reprend son compte à la suite d'une erreur il doit tout recommencer hormis nom et mot de passe

Je ne suis pas sûr de comprendre ce que tu veux dire par là ?

**Comment by ya-web** [comment]
#https://github.com/telabotanica/naturadapt/issues/70 ta réponse était  
> @ya-web oui si vous voulez on peut ajouter une étape de vérification supplémentaire... mais ça fait pas mal de boulot en plus. Je me dis que comme c'est du soft-delete, en cas de hack ou de fausse manip on peut assez facilement rétablir le compte.

on peut facilement rétablir le compte

**Comment by ya-web** [comment]
en fait au départ j'avais compris que les infos de l'utilisateur devaient être changées (mail, name display_name) pour certaine et d'autres supprimées en base puisque j'ai lu 


>     * lorsqu'on supprime le compte toutes les infos personnelles sont supprimées, mais l'User reste en base avec un nom générique et un flag `deleted`.

mais si il doit pouvoir reprendre son compte il y a des infos à conserver, name, display_name, mail, password et les infos internes comme created-at et seen-at mais les infos perso supprimées
Mais qu'est-ce qu'on fait des infos avec des clés étrangères
site, avatar, etc.

**Comment by Spone** [comment]
Oui il faut entrer un peu plus dans le détail et concevoir la meilleure solution technique / UX.

Je vois quelques pistes :

1. confirmation par e-mail comme tu proposais, et en cliquant sur un lien dans le mail on déclenche le soft-delete. On anonymise le compte et on ne garde aucune donnée perso.
2. on marque le compte comme "à soft-delete" et on déclenche le soft-delete (ce qui comprend la suppression irréversible de certaines données perso) seulement x jours après la demande, ce qui laisse le temps d'annuler en cas de fausse manip. Après x jours, on supprime effectivement toutes les données perso (site, avatar etc.) ce qui rend l'opération irréversible.

Donc ta solution de confirmation par e-mail est peut-être plus simple à mettre en place, je ne connais pas assez bien Symfony pour savoir :)

**Comment by ya-web** [comment]
Alors merci de ta réponse :wink:
Mais je proposais juste de vérifier l'identité (password et éventuellement mail) de l'utilisateur, ce que j'ai résolu (?) en supprimant simplement l'utilisateur connecté.
Par contre si je prends tes propositions ton point 2 me semble vraiment pas simple à réaliser.
Je propose de supprimer les infos perso et modifier les autres (name et display_name en "Ancien utilisateur n°<user-id>" etc), pas de retour sur la supression et comme  Killian me l'a proposé, pour s'assurer qu'il n'y a pas d'erreur de manipulation, d'ajouter au bloc de suppression un champ où il faut saisir manuellement "supprimer mon compte définitivement" à checker (const DELETE_USER_CHECK_STRING = cette phrase).
Par contre, à voir comment gérer les langues.

**Comment by Spone** [comment]
> pour s'assurer qu'il n'y a pas d'erreur de manipulation,

Je suggérais l'utilisation de `window.confirm` en JS qui joue ce rôle là nativement, mais si vous voulez on peut en effet ajouter un input

**Comment by Spone** [comment]
> Mais je proposais juste de vérifier l'identité (password et éventuellement mail) de l'utilisateur, ce que j'ai résolu (?) en supprimant simplement l'utilisateur connecté.

Oui c'était évident pour moi donc je ne l'avais pas précisé : la page de gestion du compte n'est accessible qu'en étant connecté, donc c'est bien l'utilisateur connecté qui sera supprimé. D'ailleurs il faudra aussi penser à le déconnecter et à afficher un message de confirmation "Votre compte a bien été supprimé".

**Comment by ya-web** [comment]
Ok j'ai déjà fini tout ça hier soir, (avec `window.confirm`).
Pour finir, 2 choses:

- Ce qui me parait évident c'est qu'il faut supprimer l'avatar lui même, donc l'image et évidemment la référence chez le user. Mais pour le site, comme je ne vois pas lors de la création d'un profile de vérification ou de lien avec les sites existants ça reste un site/un utilisateur donc je suppose qu'il faut aussi le supprimer, une entrée site ne peut pas être référencé par plusieurs utilisateurs.
Soyons clairs concernat le tag deleted on parle d'un STATUS_DISABLED, et pas d'un ROLE_USER_DISABLED on est bien d'accord?

**Comment by Spone** [comment]
Je ne sais pas répondre là-dessus, je ne suis pas entré dans les détails du fonctionnement de l'app Symfony.

Peut-être que @zemax aura quelques minutes pour te répondre ?

**Comment by verovs** [comment]
ping à @kstefanini

**Comment by zemax** [comment]
L'avatar du User est une entity File, donc tu peux supprimer le fichier "physique" avec le service FileManager->deleteFile($user->getAvatar());
Ensuite l'entity File elle-même peut-être supprimée, ou elle doit l'être automatiquement si on fait un $user->setAvatar(null) vu qu'il y a les orphansRemoval

Pour le site du User, c'est une entity Site et plusieurs Users peuvent faire référence au même Site. Je ne pense pas que ça soit très grave s'ils ne sont pas nettoyés, histoire de composer une base de Sites proposés en auto-complétion, mais c'est plus un choix métier que dev.

Pour le status, initialement je pensais au STATUS_DISABLED qui existe déjà ?

**Comment by ya-web** [comment]
Merci @zemax de tes réponses

**Comment by verovs** [comment]
les contenus semblent bon.
par contre je reste présent dans le compte des membres affiché dans la "home" d'un projet



![Capture d’écran de 2020-11-19 11-43-36](https://user-images.githubusercontent.com/22638189/99663291-a64c9680-2a66-11eb-8d75-6c77e81a5c28.png)
https://naturadapt.etamin.studio/groups/groupe-pas-acceptable

![Capture d’écran de 2020-11-19 11-53-53](https://user-images.githubusercontent.com/22638189/99663303-acdb0e00-2a66-11eb-8d20-4c8583a845a1.png)
https://naturadapt.etamin.studio/groups/atolls

**Comment by ya-web** [comment]
Pas réussi à reproduire le bug y compris sur le server de test mon profil disparait bien des membres du groupe

**Comment by verovs** [comment]
reproduis à l'instant 2 x.
premier user, comptetemp1@yop, a créé son profil, a rempli son nom, sa ville, à créé une actu sur comunauté (> 11 membres sur communauté), a supprimé son compte > compte membre tjs 11
second user, comptetemp2, a créé son profil, à rempli son nom, sa ville, n'a créé aucun contenu (> 12 membres) > a supprimé son compte > compte membres tjs 12
tes comptes a toi ils ont fait quoi comme action différente de moi @ya-web  ?

**Comment by ya-web** [comment]
c'était un compte existant je vais essayer avec un nouveau compte

**Comment by ya-web** [comment]
ils apparaissent où exactement je vois pas ces comptes

**Comment by ya-web** [comment]
j'avais pas compris que tu parlais du nombre de membres

**Comment by ya-web** [comment]
#236

**Comment by Spone** [comment]
> corrigé dans #236

pour info @ya-web si tu écris "Close #71" dans la description de la PR, ça fera automatiquement le lien et ça fermera automatiquement l'issue quand la PR sera mergée :)

**Comment by ya-web** [comment]
Merci je savais pas, mais c'est pas à moi de close, en plus la PR était pas mergée :)

**Comment by verovs** [comment]
ça marche !
