### ISSUE TITLE
Se désinscrire d'un groupe

### ISSUE THREAD

**Issue by verovs** [telabotanica/naturadapt#72]
On devrait pouvoir se désinscrire d'un groupe auquel on est inscrit 
Possiblement en re-cliquant sur le bouton "Inscrit"
![Capture d’écran de 2019-06-18 11-43-18](https://user-images.githubusercontent.com/22638189/59671674-59ec8f80-91be-11e9-8d3e-323f878845b5.png)

**Comment by Spone** [comment]
En fait je pense qu'il faudrait que ce bouton inscrit se comporte comme un menu déroulant permettant de choisir le niveau d'implication qu'on veut avoir avec le groupe :

- **Membre abonné** (on reçoit la newsletter et les éventuelles notifications du groupe, ce serait le cas par défaut)
- **Membre** (on reste dans le groupe, mais on ne reçoit pas la newsletter)
- **Quitter le groupe**

L'inspiration : regardez en haut de cette page Github
![image](https://user-images.githubusercontent.com/38524/59671935-d7180480-91be-11e9-91ce-0a4e1109ac0d.png)

**Comment by verovs** [comment]
fait !
