### ISSUE TITLE
Inscription/Connexion : traduire tooltips en fr.

### ISSUE THREAD

**Issue by verovs** [telabotanica/naturadapt#73]
![Capture d’écran de 2019-06-17 13-56-28](https://user-images.githubusercontent.com/22638189/59671917-d3847d80-91be-11e9-934b-4efc73c242c1.png)

> Veuillez remplir ce champ

**Comment by Spone** [comment]
Est-ce que ce serait pas un message géré par le navigateur ?

**Comment by verovs** [comment]
ha ! Je vais enquêter là dessus

**Comment by Spone** [comment]
Je confirme après avoir testé sur un Firefox en français, c'est bien un message géré par le navigateur, qui dépend donc de la langue de celui-ci. Je ferme.
