### ISSUE TITLE
Config. groupe : preview images ou indication liaison

### ISSUE THREAD

**Issue by verovs** [telabotanica/naturadapt#76]
Actuellement, sur le studio.com, lorsque l'on créé un groupe, on peut uploader des photos (avatar & couverture) mais rien ne montre que nos uploads ont été pris en compte. (mais ça marche).
Il faudrait soit faire une preview, soit mettre une indic comme quoi le fichier est bien lié, soit autre ?
![creationgroupeuploadimage](https://user-images.githubusercontent.com/22638189/59673704-08de9a80-91c2-11e9-80bf-cf795deb0f1b.png)

**Comment by Spone** [comment]
De mon côté (Firefox 67 sur Ubuntu), quand j'arrive sur https://naturadapt.etamin.studio/user/profile/create après avoir validé mon adresse e-mail, l'image est cassée.

![image](https://user-images.githubusercontent.com/38524/59674187-10eb0a00-91c3-11e9-93fb-c1747ad2cd28.png)

![image](https://user-images.githubusercontent.com/38524/59674220-22ccad00-91c3-11e9-804d-7823868cc0e5.png)

En revanche après avoir cliqué sur Parcourir et choisi un fichier j'ai bien :

![image](https://user-images.githubusercontent.com/38524/59674248-31b35f80-91c3-11e9-935c-203b39a7802b.png)
![image](https://user-images.githubusercontent.com/38524/59674253-35df7d00-91c3-11e9-9c85-af37ec4cc0db.png)

**Comment by Spone** [comment]
Ah pardon, je parle du formulaire de profil et @verovs parle du formulaire de groupe ! Je confirme que j'ai bien le problème décrit par @verovs sur le formulaire de groupe.

**Comment by zemax** [comment]
J'ai aussi le soucis mais ça dépend des images.
Je vais enqueter.

**Comment by Spone** [comment]
En fait j'ai remarqué que contrairement au formulaire de profil, celui de groupe ne contient jamais d'élément `<img>` (ni avant ni après la sélection d'un fichier)

![image](https://user-images.githubusercontent.com/38524/59674789-4a704500-91c4-11e9-90ea-f92cd7e9a161.png)

**Comment by zemax** [comment]
Ca devrait être fixé depuis le commit a5b782c32d75446049a8d8a56abce5fdcbabf198 ?

**Comment by Spone** [comment]
Oui c'est bon !
