### ISSUE TITLE
Annuaire : utiliser le nom complet

### ISSUE THREAD

**Issue by Spone** [telabotanica/naturadapt#78]
![image](https://user-images.githubusercontent.com/38524/59675132-ef8b1d80-91c4-11e9-877d-af8719551935.png)

Ici il faudrait afficher le nom complet des membres et pas le `displayname`.

**Comment by zemax** [comment]
Ah ? On n'utilise pas le nom souhaité pour l'affichage ? Et dans les autres endroits ?

**Comment by Spone** [comment]
Selon moi, le champ `displayname`, intitulé "Comment doit-on vous appeler ?" correspond plutôt aux interactions avec la plateforme (le "Bonjour Hans" sur le tableau de bord par exemple). Il n'est pas garanti d'être unique.

Je pense que dans l'annuaire et les futures discussions, il faudrait plutôt utiliser les noms complets dans ce cas.

Qu'en penses-tu @verovs ?

**Comment by zemax** [comment]
Donc y'a juste dans le "Bonjour XXX" que sert le displayName ?

**Comment by Spone** [comment]
Oui et dans les mails qu'on va envoyer à l'utilisateur.

**Comment by verovs** [comment]
J'ai pas vraiment réfléchi et j'ai pas vraiment d'avis tranché en fait (mais oui je commente quand même) Plutôt ok pour l'affichage du nom complet dans l'annuaire en tout cas.
