### ISSUE TITLE
Lien vers l'annuaire général

### ISSUE THREAD

**Issue by Spone** [telabotanica/naturadapt#79]
Pour le moment, il n'y a aucun moyen d'accéder à l'annuaire de tous les membres de la plateforme (groupe général "Communauté")

**Comment by zemax** [comment]
Le groupe général peut maintenant être défini via une variable d'env COMMUNITY_SLUG

**Comment by zemax** [comment]
(Il existe aussi l'URL /members qui liste tous les utilisateurs)

**Comment by Spone** [comment]
Super !
