### ISSUE TITLE
Profil utilisateur

### ISSUE THREAD

**Issue by Spone** [telabotanica/naturadapt#8]
https://xd.adobe.com/view/fadc33db-9c84-4133-6ae0-c1bd5539049f-8ced/screen/0f62850b-9d93-4d9f-ad2c-e220af14b2a3/Page-profil-1?hints=off

- [x] ajouter les infos manquantes (ville, compétences)

- [x] ajouter un lien pour modifier son profil

- [x] ajouter la liste des groupes dont l'utilisateur est membre

**Comment by Spone** [comment]
@chikencheesenaan est-ce qu'on pourrait afficher les compétences comme des "tags" pour faire le lien avec les autres endroits du site où on les affiche.

![image](https://user-images.githubusercontent.com/38524/59567871-98296800-9073-11e9-9a47-c2bfb92e7098.png)
:arrow_down: 
![image](https://user-images.githubusercontent.com/38524/59567879-b2fbdc80-9073-11e9-957f-bdb555dd5c62.png)

Et pour les groupes ce serait bien de les afficher comme sur l'accueil des groupes, sous forme de "cartes" : 
![image](https://user-images.githubusercontent.com/38524/59567892-d4f55f00-9073-11e9-998a-cca2b964eb46.png)
:arrow_down: 
![image](https://user-images.githubusercontent.com/38524/59567901-e9395c00-9073-11e9-84b0-80bb9963765e.png)

**Comment by chikencheesenaan** [comment]
C'est MAJ

**Comment by Spone** [comment]
Remonter ce bouton en haut à droite : 
![image](https://user-images.githubusercontent.com/38524/59773937-ccd53380-92ae-11e9-8af9-e7e970fb4be5.png)

et le renommer "Contacter par e-mail"

**Comment by Spone** [comment]
Enlever les 
![image](https://user-images.githubusercontent.com/38524/59773962-dc547c80-92ae-11e9-86d8-b2fdf56c7004.png)

**Comment by chikencheesenaan** [comment]
🔄

**Comment by Spone** [comment]
Du coup @zemax on a refait une passe sur le design du profil, peux-tu mettre à jour l'inté ?

**Comment by Spone** [comment]
@zemax peux-tu avancer là-dessus en priorité ? Au moins avoir le bouton "Contact"

**Comment by zemax** [comment]
Résolu sur 8b9f46d85369cc54531640eb58d25960a2f7f27e

**Comment by Spone** [comment]
Super, merci !

**Comment by Spone** [comment]
Il faudrait remonter le bouton "Contact" en haut à droite et le renommer "Contacter par e-mail", comme sur la maquette https://xd.adobe.com/view/fadc33db-9c84-4133-6ae0-c1bd5539049f-8ced/screen/0f62850b-9d93-4d9f-ad2c-e220af14b2a3/Page-profil-1/?hints=off

**Comment by zemax** [comment]
fixé sur c44bb77e89e5899dfdb9638fbc29d13f170396d3

**Comment by zemax** [comment]
rajouté sur 2284de409a84ff12c0ceb231609ef422b710149d
