### ISSUE TITLE
CK editor : proposer des iframes pour les pages des groupes

### ISSUE THREAD

**Issue by verovs** [telabotanica/naturadapt#80]
Hier, sur le staging (^^) j'avais rempli la description du groupe plateforme web. Avec touuuut les boutons possibles.
Aujourd'hui, j'ai créé une page, dans ce même groupe, c/c mon texte et en fait l'éditeur ne propose plus les mêmes choses.
Autant je suis ok pour enlever de la description groupe les imgs/tables/iframe, elles ne servent à rien
Autant pour **les pages**, ça serait nécessaire d'avoir le bouton iframe (table je vois pas trop l’intérêt), et c'est bien d'avoir img (comme actuellement !)

![Capture d’écran de 2019-06-18 18-24-21](https://user-images.githubusercontent.com/22638189/59702602-5f66cb80-91f8-11e9-9f90-d4a4a50f4a0e.png)
screen de la présentation du groupe plateforme, aujourd'hui, txt fait hier, l'éditeur n'a plus les même boutons

![Capture d’écran de 2019-06-18 17-35-04](https://user-images.githubusercontent.com/22638189/59702702-9806a500-91f8-11e9-8d31-b2957de90629.png)
screen de la barre éditeur actuelle d'une page dans un groupe
https://naturadapt.etamin.studio/groups/plateforme-web/pages/presentation-123

![Capture d’écran de 2019-06-18 18-28-42](https://user-images.githubusercontent.com/22638189/59702807-e1ef8b00-91f8-11e9-85dc-c148b6a05079.png)
Ce que j'aimerai qu'on remette, sur les éditeurs wysiwig des pages de groupe

(C'est possible aussi que ce soit juste sous mes yeux et que je ne le trouve pas, j'en suis désolée d'avance si c'est le cas ^^' )

**Comment by zemax** [comment]
Pour les images, on ne peut pas les avoir lors de la création du groupe (car tant que le groupe n'est pas créé, on ne peut pas uploader d'images associées au groupe dans le wysiwyg)
Pour les autres fonctions je regarde pour les reactiver

**Comment by verovs** [comment]
pas de souci pour les groupes, c'est vraiment pour les pages :)

**Comment by zemax** [comment]
OK c'est rétabli

**Comment by verovs** [comment]
super ! C'est pas encore pris en compte ds l'affichage par contre : https://naturadapt.etamin.studio/groups/plateforme-web/pages/presentation-123 (mais c'est pt être un autre ticket )

**Comment by zemax** [comment]
Oui il n'y a pas encore de style par défaut pour l'affichage des table ou des quote
