### ISSUE TITLE
Fil d'Ariane : dernier item blanc transparent

### ISSUE THREAD

**Issue by Spone** [telabotanica/naturadapt#81]
Peux-tu utiliser un blanc transparent pour le dernier item plutôt qu'un gris comme actuellement ?
Histoire d'être plus lisible sur les différents fonds...

Par exemple là ça pose problème :

![image](https://user-images.githubusercontent.com/38524/59710706-c640b080-9209-11e9-9524-2219f0a4a1d9.png)

**Comment by zemax** [comment]
corrigé sur d2cab21d966aab07ce1a014d80ea5634247b1986
