### ISSUE TITLE
Style par défaut pour les <table> et les <blockquote>

### ISSUE THREAD

**Issue by zemax** [telabotanica/naturadapt#82]
Ca pourrait être bien d'avoir un style par défaut pour les éléments `<table>` et `<blockquote>` résultant du wysiwyg, ex https://naturadapt.etamin.studio/groups/plateforme-web/pages/presentation-123

**Comment by Spone** [comment]
Que pensez-vous de reprendre le style "[default blockquote](https://getbootstrap.com/docs/3.4/css/#default-blockquote)" de Bootstrap v3 et le style "[bordered table](https://getbootstrap.com/docs/4.3/content/tables/#bordered-table)" de Bootstrap v4 ?

**Comment by zemax** [comment]
J'ai rajouté un style semblable à Bootstrap.

**Comment by Spone** [comment]
:+1:
