### ISSUE TITLE
Footer : logo et liens

### ISSUE THREAD

**Issue by Spone** [telabotanica/naturadapt#86]
![image](https://user-images.githubusercontent.com/38524/59774156-45d48b00-92af-11e9-893c-efcba8ddb85a.png)

- [x] Ajouter le logo LIFE
- [x] Changer les liens pour avoir un lien "Accueil" + un seul lien "Inscription / Connexion"

**Comment by zemax** [comment]
Peux-tu m'envoyer le logo Life en vecto de préférence ?
Vers quoi pointe le lien "A propos..." ?

**Comment by verovs** [comment]
A propos de la plateforme pointera sur une page créé dans le groupe communauté (si @Spone  est ok avec cette architecture ?)  ça donnerait, en me basant sur le slug du staging (!) https://naturadapt.etamin.studio/groups/plateforme-web/pages/presentation-123
https://naturadapt.com/groups/communaute/pages/a-propos-de-la-plateforme
je te cherche le logo life (si je le trouve sur le web en vecteur)

**Comment by verovs** [comment]
logo vecteur : http://ec.europa.eu/environment/archives/life/toolkit/comtools/resources/documents/life.ai (mais il a pas vraiment une tête de vecteur ?)
lui il est mieux : http://ec.europa.eu/environment/archives/life/toolkit/comtools/resources/images/life.eps
il te le faut en quel format ?

**Comment by zemax** [comment]
Merci, le eps est bien

**Comment by zemax** [comment]
J'ai rajouté le logo Life

**Comment by Spone** [comment]
Ok manque plus que le lien "A propos de la plateforme"

**Comment by verovs** [comment]
Vous pouvez la créer et écrire 'En cours' :) 
J'aurai pas vraiment le temps de faire mieux avant lundi (pt-être que je la modifierai ce dimanche)

**Comment by Spone** [comment]
Du coup ce serait une page dans le groupe "Communauté"

**Comment by Spone** [comment]
Véro tu peux la modifier ici : https://naturadapt.com/groups/communaute/pages/a-propos-de-la-plateforme

**Comment by Spone** [comment]
J'ai fait les modifs sur les liens du footer pour éviter d'avoir des liens cassés.
