### ISSUE TITLE
Ajout d'un document : préremplir le nom du document

### ISSUE THREAD

**Issue by Spone** [telabotanica/naturadapt#87]
![image](https://user-images.githubusercontent.com/38524/59911480-4b97b100-9414-11e9-9ca6-f6c5da2904ef.png)

Est-il possible, sur le même principe que l'aperçu de l'image de profil une fois qu'on a sélectionné un fichier, de pré-remplir le champ "Nom du document" avec le nom du fichier sélectionné (en enlevant son extension) ?

**Comment by zemax** [comment]
ajouté sur ba41ff325fd7eff029b9a28b79aa1684f198d24a
