### ISSUE TITLE
Carte de groupe : cliquable en entier

### ISSUE THREAD

**Issue by Spone** [telabotanica/naturadapt#88]
![image](https://user-images.githubusercontent.com/38524/59911577-88fc3e80-9414-11e9-8b9d-58e9d2febeef.png)

Peut-on rendre l'ensemble de la carte cliquable, et pas juste le titre ? On peut utiliser la méthode de "lien composite" décrite ici : https://pidila.gitlab.io/scampi/documentation/lien-composite.html

Au passage, peut-on ajouter un effet de survol ?

**Comment by zemax** [comment]
Pourquoi ne pas utiliser un lien sur le bloc directement plutôt qu'un lien composite ?

**Comment by Spone** [comment]
Pour des raisons d'accessibilité comme expliqué sur le lien Pidila ;)

> Le lien composite permet d'éviter deux écueils :
>
> - la juxtaposition de liens adjacents conduisant tous vers la même cible ;
> - une imbrication dans un élément <a> de tous les éléments composant le bloc cliquable, rendant ainsi la restitution vocale "trop bavarde".

**Comment by zemax** [comment]
ajouté sur b63f1134727a180dea1735ed9bdaeccde234c1a0

**Comment by Spone** [comment]
Sur le staging, chez moi tout est cliquable sauf l'image

**Comment by Spone** [comment]
Super c'est corrigé :)

**Comment by Spone** [comment]
Pardon je réouvre en fait j'ai un problème d'affichage des icônes des groupes :

![image](https://user-images.githubusercontent.com/38524/60117172-d14f8f80-9779-11e9-93f8-973d35d0bc63.png)

**Comment by zemax** [comment]
zut j'avais oublité de modifié le top: en margin-top:
C'est corrigé sur 0161c38536140e337735b80a5fe1f9c5d4120365

**Comment by Spone** [comment]
Merci
