### ISSUE TITLE
Liste des groupes : ordre

### ISSUE THREAD

**Issue by Spone** [telabotanica/naturadapt#89]
Dans quel ordre sont triés les groupes ?

Il faudrait que le groupe Communauté soit toujours en premier, puis les autres groupes dans l'ordre décroissant de date de dernière activité.

**Comment by zemax** [comment]
fixé sur 210e479be42ac4241767f2a144412e335f540f4b

**Comment by zemax** [comment]
(je réouvre car c'est classé par date de création décroissante et pas de dernière activité pour le moment)

**Comment by zemax** [comment]
fixé dans df44b7d369bbe30aa6a986bdbd3fe8772c107a8a
