### ISSUE TITLE
Formulaire profil utilisateur

### ISSUE THREAD

**Issue by Spone** [telabotanica/naturadapt#9]
Création de profil : https://xd.adobe.com/view/fadc33db-9c84-4133-6ae0-c1bd5539049f-8ced/screen/0f6afa32-8418-42b1-bcfd-acd347195d8a/Page-inscription?hints=off

Édition de profil : https://xd.adobe.com/view/fadc33db-9c84-4133-6ae0-c1bd5539049f-8ced/screen/2169079a-d753-49b4-8398-a0c148612787/Page-Profil-Perso?hints=off

- [x] ajouter un lien pour voir son profil

**Comment by Spone** [comment]
@chikencheesenaan Le risque, en mettant le lien 
![image](https://user-images.githubusercontent.com/38524/59567941-0cfca200-9074-11e9-9fc6-81eaa7d247db.png)
en bas à côté du bouton de sauvegarde, est que les gens cliquent dessus après avoir fait des changements, et donc ne sauvegardent pas leurs changements...

Il faudrait remonter ce bouton en haut, à côté de ça :

![image](https://user-images.githubusercontent.com/38524/59567953-2867ad00-9074-11e9-8cf3-7e784de50ec1.png)

**Comment by chikencheesenaan** [comment]
ok ! :)
