### ISSUE TITLE
Remplacer l'icône "cadenas"

### ISSUE THREAD

**Issue by Spone** [telabotanica/naturadapt#90]
On a refait l'icône cadenas pour qu'elle soit plus compréhensible : 
![image](https://user-images.githubusercontent.com/38524/59912814-25bfdb80-9417-11e9-8ff6-e77b204faeaf.png)

**Comment by zemax** [comment]
Où puis-je trouver ce nouvel icone ?

**Comment by Spone** [comment]
@chikencheesenaan tu peux faire un SVG ?

**Comment by chikencheesenaan** [comment]
Idem valable 1 semaine : https://fil.email/zH6oId1a

**Comment by Spone** [comment]
@zemax tu pourras t'en occuper ? :)

**Comment by verovs** [comment]
Lien pérenne : http://taiga.tela-botanica.net/media/attachments/9/4/5/f/10569a82f3f6f548ad1aff4fd5eec44773fa4bc39271ac35b088c6c5bdfc/lock.svg

**Comment by verovs** [comment]
alors ça maintenant je peux pt etre le faire 
je me l'assigne pour voir si c'est réalisable
