### ISSUE TITLE
Message quand on doit se connecter

### ISSUE THREAD

**Issue by Spone** [telabotanica/naturadapt#91]
Actuellement si je ne suis pas connecté et que j'essaie de voir le profil de quelqu'un, on m'affiche la page de login (normal).

Ce serait bien d'avoir un message flash du type : "Vous devez vous inscrire ou vous connecter pour voir cette page."

**Comment by zemax** [comment]
Résolu sur df6449f70979ac136a2f84b888e8f560b4577b9f
