### ISSUE TITLE
Page login : rediriger sur l'accueil quand connecté

### ISSUE THREAD

**Issue by Spone** [telabotanica/naturadapt#92]
Si je suis connecté et que je visite https://naturadapt.com/user/login je vois les formulaires. Il faudrait plutôt rediriger sur le dashboard avec un flash message "Vous êtes déjà connecté·e.".

**Comment by zemax** [comment]
fixé sur eba2338d539d1b40ad2aed944e821c3572134390

**Comment by zemax** [comment]
(d397fdbb8986ee7d93b70a6d833aba072a0d476d)
