### ISSUE TITLE
Accueil groupe : hauteur fixe des "cartes"

### ISSUE THREAD

**Issue by Spone** [telabotanica/naturadapt#93]
Actuellement :

![image](https://user-images.githubusercontent.com/38524/59916056-738c1200-941e-11e9-9c8b-8d029eb50001.png)

Maquette :

![image](https://user-images.githubusercontent.com/38524/59916025-62430580-941e-11e9-94bc-a9e087362532.png)

**Comment by zemax** [comment]
Ajouté sur 8d2d691414a19f87682cfa9b2c19995930a03e6a
