### ISSUE TITLE
largeur fixe des cartes (groupes) - ou si un nom de doc est trop long, il casse le layout

### ISSUE THREAD

**Issue by verovs** [telabotanica/naturadapt#95]
ici https://naturadapt.etamin.studio/groups/plateforme-web

(ma théorie : le nom du fichier xls (le dernier) est trop long. du coup la carte s'est adaptée à la largeur. et elle a basculé en dessous > Au bout de X char. couper le nom du doc)

Une capture d'écran vous aidera mieux que 1000 de mes mots.

![Capture d’écran de 2019-06-21 15-41-15](https://user-images.githubusercontent.com/22638189/59926773-49951880-943b-11e9-89fb-d2b73df3fb32.png)

lien https://naturadapt.etamin.studio/groups/plateforme-web

**Comment by zemax** [comment]
Résolu sur 7cdf528fe6298dc4c04544a6eac6d5a60507f382
