### ISSUE TITLE
[Prod] supprimer un doc

### ISSUE THREAD

**Issue by verovs** [telabotanica/naturadapt#98]
Dans les docs, on peut pas encore les supprimer. Dans le futur il faudrait.
Pour l'instant :
Pouvez vous supprimer en BDD mon non-fichier (j'ai cliqué sur envoyer alors que j'avais rien mis *boulet*) svp 
https://naturadapt.com/groups/plateforme-web/documents

>  /groups/plateforme-web/documents/2/get

**Comment by zemax** [comment]
Peux-tu tester en allant sur https://naturadapt.com/groups/plateforme-web/documents/2/delete ?
Le mécanisme de suppression existe, mais il n'est pas encore intégré dans l'interface.
Seul un admin du groupe ou le propriétaire du document peut le supprimer.

**Comment by verovs** [comment]
ça marche ! trop bien merci :)
