### ISSUE TITLE
Durée des sessions ?

### ISSUE THREAD

**Issue by Spone** [telabotanica/naturadapt#99]
Combien de temps durent les sessions ? J'ai l'impression qu'à chaque fois que je reviens sur la plateforme je dois me connecter à nouveau.

**Comment by zemax** [comment]
Je pense que les sessions PHP sont stockées dans un rep temporaire qui est vidé à chaque rebuild de Clever-cloud

**Comment by Spone** [comment]
Je vois ça dans les options Clever Cloud mais je pense pas que ce soit lié car on utilise pas le scaling pour le moment :

![image](https://user-images.githubusercontent.com/38524/60080982-316e1380-9731-11e9-8ae6-f0ffd2bd9d88.png)

**Comment by Spone** [comment]
Je vais poser la question au support Clever Cloud.

**Comment by Spone** [comment]
Je viens de tester en me connectant et en lançant ensuite un rebuild/restart de l'app. La session est conservée. Est-ce que c'est pas un problème de configuration côté app ?

**Comment by zemax** [comment]
Le remember_me se configure ici https://github.com/telabotanica/naturadapt/blob/develop/config/packages/security.yaml 
Il est fixé actuellement à 30 jours.

**Comment by Spone** [comment]
En effet, c'est bizarre. Bon je vais essayer d'être attentif à ça pour voir si j'arrive à reproduire de manière systématique.

**Comment by Spone** [comment]
@zemax pourquoi y a-t-il une tilde pour cette option ? https://github.com/telabotanica/naturadapt/blob/develop/config/packages/framework.yaml#L10

**Comment by zemax** [comment]
C'est la syntaxe créée par défaut par Symfony. 
Je vois que la doc de Symfony 4.2 fait plutôt référence à *null* par défaut, on peut changer pour ça mais je ne pense pas que ça change grand chose.

**Comment by Spone** [comment]
Oui tu peux passer à `null` stp ?

**Comment by Spone** [comment]
J'ai l'impression qu'il y a un problème au niveau de la date d'expiration du cookie `REMEMBERME` :

![image](https://user-images.githubusercontent.com/38524/60092562-a51b1b00-9747-11e9-8562-3a64f473917d.png)

**Comment by zemax** [comment]
Bizarre, j'ai pas le soucis :
![image](https://user-images.githubusercontent.com/286485/60092746-09d67580-9748-11e9-8742-238707e45de4.png)
Tu testes sur quoi ?

**Comment by Spone** [comment]
Firefox 67 sur Ubuntu.

**Comment by zemax** [comment]
Je pense que j'ai trouvé, fixé sur le commit faf2ec7ca63cc3e7e2002a3e1cc7236391cf69b4

**Comment by Spone** [comment]
Super !
